### ISSUE TITLE
Update the MediaWiki instance

### ISSUE THREAD

**Issue by Umcaruje** [LMMS/lmms.io#108]
We are running version [1.16.0](http://www.mediawiki.org/wiki/Release_notes/1.16) Which was released 4 years ago, so I think the wiki could really use an update.

P.S. Could you install the http://www.mediawiki.org/wiki/Extension:FontAwesome extension? I'd replace a lot of the icons with the FA ones, so we keep it consistent with the website.

**Comment by Umcaruje** [comment]
I successfully updated to wiki to 1.24.1. I Left the database and data backups on the server in case something was screwed up :), but I have done some testing, and it seems to be working good.

**Comment by tresf** [comment]
Great work!  Well planned ans executed!

**Comment by Lukas-W** [comment]
Cool, thanks @Umcaruje!

**Comment by Sti2nd** [comment]
Wow, Uros, great job!

I guess you were hiding the edit links @Lukas-W and correcting the tables not showing properly :) https://lmms.io/documentation/Video_tutorials

**Comment by Lukas-W** [comment]
The wiki version we used before just didn't have those edit links.
The tables always looked like this, the page uses some custom CSS that doesn't show properly on our main page.

**Comment by Umcaruje** [comment]
I'll see what I can do about removing those edit links :)

**Comment by tresf** [comment]
Getting Started is broken... 

https://lmms.io/documentation/Getting_Started&action=edit&redlink=1

Might be a cache problem though.... as this link seems to work:

https://lmms.io/documentation/Getting_Started

As far as the "Edit" buttons, you should be able to just do `display:none` on CSS class `mw-editsection` in `style.css` and it will hide it, but only when being displayed within our header/footer.

-Tres

**Comment by Umcaruje** [comment]
>Getting Started is broken...

>https://lmms.io/documentation/Getting_Started&action=edit&redlink=1
Might be a cache problem though.... as this link seems to work:

>https://lmms.io/documentation/Getting_Started

Made a pointless edit, and it recached and it works properly now :)

>As far as the "Edit" buttons, you should be able to just do display:none on CSS class mw-editsection in style.css and it will hide it. This should be fine as it would only hide when being displayed within our header/footer.

That's an awesome idea, I'll do that.

**Comment by Umcaruje** [comment]
Fixed the edit button per https://github.com/LMMS/lmms.io/commit/e496dfeddbad9d6f1f0f5b6a0be12b9b82cedaef Thanks @tresf

**Comment by Lukas-W** [comment]
@Umcaruje It's probably cleaner to use MediaWiki's API's `disableeditsection` option, see https://lmms.io/wiki/api.php (search for action=parse)

**Comment by tresf** [comment]
> @Umcaruje It's probably cleaner to use MediaWiki's API's disableeditsection option, see https://lmms.io/wiki/api.php (search for action=parse)

Good call, although that would only benefit direct wiki visitors (those that don't use it through the Documentation link) and since we have no link to the direct wiki, that would disable the edit button for content authors, right?  In this case, hiding it might be cleaner from the perspective of our authors.

-Tres

**Comment by tresf** [comment]
Another option is to actually make the edit button usable and enabled everywhere, just not as intrusive....

**Comment by Lukas-W** [comment]
No it'd only affect `/documentation`.

**Comment by Sti2nd** [comment]
> Video Tutorials page seems to use some custom CSS that doesn't show properly on our main page.

@Lukas-W It indeed does, I copied it from which doesn't work fully either, but it looks better https://lmms.io/documentation/Tested_VSTs 
Maybe there is a sortable table function in MediaWiki.

**Comment by Umcaruje** [comment]
I'll soon start adding CSS rules to fix these inconsistencies. I'll make a WIP Pull Request, so you can see the progress.

**Comment by Sti2nd** [comment]
Looks better now Uros https://lmms.io/documentation/Video_tutorials
The function we lack is to make the tables sortable.

**Comment by tresf** [comment]
> No it'd only affect /documentation.

Great.  Uros to Lukas' point, if you know how to switch that setting it is better than hardcoding mediawiki hacks into our style.css. :)
