### ISSUE TITLE
Update proboot3 to ComBoot

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms.io#114]
Per proboot3 developer:

> ComBoot is just the new name of proBoot3. So its simple a name change according to the first stable release of this theme.
>
> So you can update to the latest version (offered here on github) without loosing any feature or anything..
>
> If you unsure, what comboot looks like (it looks almost as proBoot3 does) you can checkout the demo:
http://comboot.de/demo/free/
>
> Hope I could help you :)
>
> If you have any further question, just comment [here](https://github.com/TheZoker/ComBoot/issues/23) :)

-Tres

**Comment by Umcaruje** [comment]
@TheZoker I just updated the forums to phpbb 3.1, and then realised ComBoot is not available for 3.1 yet :disappointed: 

Do you have an estimate of when ComBoot will be available for 3.1?

I might have to undo all the work I've done today ...

**Comment by tresf** [comment]
@Umcaruje, please don't revert just for a theme.  If you find one that you feel works well for our site (and phpBB3) please link it here and we'll use it for the interim.

Most phpBB3 themes are under $20 USD, which we have available in our funds.

-Tres

**Comment by TheZoker** [comment]
@Umcaruje @tresf I work on a version for 3.1 and hopefully can finish it until end of this week. I will let you know, if its ready :)

**Comment by tresf** [comment]
@Umcaruje if (for now) you could hack in a link to the main site (for navigation purposes), we can get by with a bare-bones phpBB until Zoker's ready.

**Comment by Umcaruje** [comment]
Ok I'll see what I can do :)

**Comment by Umcaruje** [comment]
The PhpBB link now goes to the website also there is a link to the main website on the nav panel

**Comment by tresf** [comment]
Fantastic! That should hold us off for now.

**Comment by Umcaruje** [comment]
@TheZoker any update on the theme port?

**Comment by TheZoker** [comment]
Im nearly finished, only some files are left and I need to fix some bugs :)

**Comment by Umcaruje** [comment]
Awesome :+1:

**Comment by TheZoker** [comment]
Sorry for the delay...
I had some private stuff to handle with. I will try to complete the new version until Monday (may it has some bugs, but you can tell me then).

**Comment by Umcaruje** [comment]
@TheZoker any updates? Is there a beta/unstable version that we could use? I might even go and fix those issues myself when I get the time, since this is a terrific theme.

**Comment by Umcaruje** [comment]
@tresf since it seems that ComBoot development is currently frozen, do you know some place where we could get a nice theme with bootstrap for the forums?

**Comment by tresf** [comment]
Not currently, but we have about $60 left after the domain renewal to invest. :)

**Comment by TheZoker** [comment]
Sorry for the late response guys! My study currently takes my complete time :/
But I try to release a beta version tomorrow or within the next week. It will probably contain some bugs, but it would be nice, if you can tell me them and we can fix them :)

**Comment by TheZoker** [comment]
Closed beta is available! Read more here: http://comboot.io/blog/beta/beta-3-1/

**Comment by softrabbit** [comment]
Closing, as forum says "Design: ComBoot by Florian Gareis"
