### ISSUE TITLE
LSP: Unable to link to Soundcloud playlists

### ISSUE THREAD

**Issue by Fastigium** [LMMS/lmms.io#124]
Hey, I tried linking to the Christmas Contest winners, but it broke :/. See it in action here:

https://lmms.io/lsp/?action=show&file=6156

It seems that the system tries to convert the first part of the playlist URL to a song player (i.e. https://soundcloud.com/username/sets), fails, and ignores the playlist name part. I hope you can fix it :)

**Comment by Umcaruje** [comment]
Zap.

**Comment by Umcaruje** [comment]
Zap.
