### ISSUE TITLE
Free audio Library integration

### ISSUE THREAD

**Issue by DeRobyJ** [LMMS/lmms.io#129]
It would be interesting to create a place with free audio tracks made with LMMS ready to use for other projects.
A place where youtubers would go searching for they background tracks, or DJs for some background music, or anyone for a music playing during any kind of project they have.

A place like http://freemusicarchive.org/ .
This freemusicarchive offers API, so we could also upload this kind of content there and then have a special page on the site (or within the LSP) which shows the tracks made with LMMS.

But in general, the key features of a place like that is:
- Music is royalty-free, ready for commercial use
- In exported audio file
- With queries like "mood" or when-to-put (party, videogame, fight, landscape, thriller and such)

Another interesting feature would be a "contact the author" service which lets the user send a request to the author of a track, like "remove that part", "make the music loopable", "make an extended mix of tot minutes".

Another interesting service is the Youtube Audio Library, while sites like freesound.org offer sounds, not tracks, and sites like SoundCloud don't have a "free for commercial use" query.

**Comment by tresf** [comment]
> It would be interesting 

Yes it would.  Perhaps an LSP2 feature.  Marking as wont-fix.
