### ISSUE TITLE
how to find topic identification number?

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms.io#134]
Need to find this *topic identification number* in order to move a post from 'News' to trouble shooting, but where is this number (using the 'search' option only display one topic, and there seams to be no way to expanding this search)

**Comment by Sti2nd** [comment]
No you don't, go to the topic you want to move, at the bottom choose move topic, then click go.
![image](https://cloud.githubusercontent.com/assets/6373430/5695415/8d2d240e-99a2-11e4-817c-b790c86f4c27.png)


Unrelated: You probably know this, but a forum is meant to have a lot of duplicate posts, that is useful when searching cause then you can find the exact wording if someone have had that problem before.

**Comment by tresf** [comment]
Should be:

![image](https://cloud.githubusercontent.com/assets/6345473/5703544/06c5f578-9a36-11e4-936f-b947ab211ba6.png)

Can you please confirm?

**Comment by tresf** [comment]
You may also be setup different than the admins... this is what I see... 

![image](https://cloud.githubusercontent.com/assets/6345473/5703588/920fb434-9a36-11e4-8d8b-f3bb2dd044b8.png)

**Comment by Sti2nd** [comment]
If you want me to move a topic, @musikBear , just ask. Tres' picture show where you come when you click "go".
