### ISSUE TITLE
User FAQ, troubleshooting section

### ISSUE THREAD

**Issue by softrabbit** [LMMS/lmms.io#135]
So, there's a recipe for routing LMMS straight to ALSA on https://lmms.io/documentation/User_FAQ#Troubleshooting but it probably doesn't work. Assuming there's only one sound device you need to start LMMS like `pasuspender -- lmms` so PA goes out of the way and LMMS can access the device.

**Comment by tresf** [comment]
That theme glitch problem was fixed with `stable-1.1` btw.  Safe to remove.

-Tres

**Comment by tresf** [comment]
> you need to start LMMS like pasuspender -- lmms so PA goes out of the way and LMMS can access the device.

Should we add this to our desktop shortcuts?  We're already overriding the Unity bar per [`lmms.desktop#L9`](https://github.com/LMMS/lmms/blob/master/data/lmms.desktop#L9)

**Comment by softrabbit** [comment]
No, not the desktop shortcut. Not unless starting LMMS by default should disable all other desktop sound, no matter which backend is configured. 

The problem with the solution presented in the User FAQ is that if PA already is using the card you configure LMMS to use and you just "restart LMMS", as the instructions tell you, it will revert to the dummy interface and LMMS will make no sound.

**Comment by tresf** [comment]
> The problem with the solution presented in the User FAQ is that if PA already is using the card you configure LMMS to use and you just "restart LMMS", as the instructions tell you, it will revert to the dummy interface and LMMS will make no sound.

Thanks for the explanation.

Since this relates a bit to https://github.com/LMMS/lmms/issues/1600, do you have PA installed to test against and offer some results?  If I have time, I'll setup a vanilla Linux box and test myself, just need to find some candidate hardware. :)

**Comment by Sti2nd** [comment]
> Safe to remove.

Done

**Comment by softrabbit** [comment]
> Since this relates a bit to LMMS/lmms#1600, do you have PA installed to test against and offer some results?

LMMS/lmms#1600 is where I got the idea to try the instructions... some testing done:
* On the first Ubuntu (14.04, possibly .10) pasuspender was required and LMMS wanted to fall back to dummy
* On the other (14.04.1) the procedure worked as advertised, LMMS got the card and PA stayed out of the way.

Maybe add a mention like:
> If the above instructions don't work and PulseAudio doesn't release the card, start LMMS using `pasuspender -- lmms`

**Comment by Sti2nd** [comment]
> If the above instructions don't work and PulseAudio doesn't release the card, start LMMS using pasuspender -- lmms

Done

**Comment by tresf** [comment]
@softrabbit want to keep this open for a bit longer until 1600 gets closed or are you happy with the documentation changes for now?

**Comment by softrabbit** [comment]
There's not an overwhelming number of open issues for lmms.io, so why not keep this for a while.

**Comment by softrabbit** [comment]
LMMS/lmms#1600 turned into something completely different, so this might just as well be closed.

**Comment by Umcaruje** [comment]
:+1:
