### ISSUE TITLE
Closing #134 before looking into the problem

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms.io#136]
It really does not make sense, just closing a topic, without actually trying to do the task
After selecting topics meant to be moved, and choosing action *Move*, a new form pops up, and thats where the issue lies:
![idnumbneed](https://cloud.githubusercontent.com/assets/6662066/5702336/f6616ba4-9a58-11e4-9cae-2efd287be648.PNG)
This **Destination topic Identification Number**
*Where* is it?
Yes - i have tried *Select topic* -Thats when only one topic is displayed
Move should be as simple as moving posts to a differen sub-forum.
Move looks like moving post into existing topics:
Choose '7' (because troubleshoot is subforum 7) will merge the selected posts into topic 7, not sub-forum 7
This is why a ask for the **Destination topic Identification Number**, because thats what the engine uses..

**Comment by tresf** [comment]
You have the ability to reopen you own bug reports.

**Comment by musikBear** [comment]
> You have the ability to reopen you own bug reports. 
really - oh well, good to know ..next time

**Comment by tresf** [comment]
> It really does not make sense, just closing a topic, without actually trying to do the task

Because this is not a support forum.  This is not a general help area for phpBB.  You are cluttering our website tracker with basic questions about the forum which we did not decide and we can't change.  Our tracker isn't for that.  Opening new bug reports won't change that.
