### ISSUE TITLE
Notifications in LSP

### ISSUE THREAD

**Issue by Sti2nd** [LMMS/lmms.io#141]
Proposal: Notifications in lsp for comments on your projects and for projects you have commented on. 
A notification could be to send out an email.

Some of you might argue that this is too big for lsp1, and should be happening in lsp2, but lsp2 isn't high priority when we now have a functional lsp, and it is probably not going to be realized within the next six months, I know I won't focus on it before the summer at least :/ So if this is possible to do with lsp1 that would be really great :D

**Comment by tresf** [comment]
We dont currently collect email addresses.

**Comment by Sti2nd** [comment]
I know, perhaps notification on site is even easier

**Comment by tresf** [comment]
We'll, that would still require the collection of read vs. unread comments,
which would be some database work.

I think its best to leave this for the rewrite.  The CMS concepts all have
this notification stuff built in.

**Comment by tresf** [comment]
Closing, out of scope for current LSP.
