### ISSUE TITLE
Broken link in online manual

### ISSUE THREAD

**Issue by murakamih** [LMMS/lmms.io#142]
On the online manual page:  https://lmms.io/wiki/index.php?title=0.4:Using_MIDI#Setting_MIDI_input.2Foutput,   Setting MIDI input/output image: <img src="http://lmms.io/wiki/screenshots/midi_in2.png" alt="midi_in2.png"> is broken

Thanks, 

Hiroshi

**Comment by Umcaruje** [comment]
That page is old and outdated. The new, updated page is on https://lmms.io/wiki/index.php?title=Using_MIDI

I'll add a 'Page moved' message. There is no point in fixing these old pages, since 0.4 isn't supported yet. Closing as a wontfix.
