### ISSUE TITLE
Facebook feed broken?

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms.io#144]
Seems like we are missing some feeds... 

![screen shot 2015-02-15 at 3 10 30 pm](https://cloud.githubusercontent.com/assets/6345473/6204768/d10695fa-b524-11e4-9ece-696c63c6430c.png)

**Comment by Umcaruje** [comment]
Seems we hit some kind of 'limit'... Since the feed hasn't changed for months.

Maybe has some connection with #146

@tresf do you have any idea on how we could solve this problem?

**Comment by tresf** [comment]
We use my hacked and ugly API currently and I think it broke with a change that was made a while ago.

We can fix it manually or we can rewrite the feed to use some better APIs and templating like Lukas has already done for the Download page.

Fixing it (or even debugging it) sucks because the feed is a spaghetti mess and I haven't the time to fix it right away.  So... I dont know. :)

**Comment by softrabbit** [comment]
https://developers.facebook.com/docs/apps/changelog#v2_3_90_day_deprecations

The new URL should be http://graph.facebook.com/v2.3/435131566543039/feed but it looks like authentication is needed even for reading (a bit draconian if you ask me).

**Comment by tresf** [comment]
Thanks @softrabbit.  I had to disable the feed to prevent the community page from failing (it must have been operating from a very old cache that was wiped away after we crashed out our tmp directory (session cleanup wasn't running for some reason).

Anyway, this community page needs an overhaul.  We use authentication for most of our APIs, so this should be straight, but since we're moving everything to silex, twig and family, this might just get guzzled up by a productive composer weekend by Mr. Lukas-dash-W.

**Comment by tresf** [comment]
I've removed the buttons from view as they serve no purpose until this is fixed.

Closing for now, but a long term solution is to use a JSON API similar to how the downloads are populated. :+1: 

![image](https://cloud.githubusercontent.com/assets/6345473/13888122/11c12090-ed16-11e5-89d3-9b63daf5ba77.png)
