### ISSUE TITLE
Downloads not showing latest (GitHub 30 results limitation)

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms.io#146]
Downloads are incorrect again, this time because we've reached our 30 results per page limitation after Toby copied over the historical source snapshots.

![image](https://cloud.githubusercontent.com/assets/6345473/6206906/9cd40572-b562-11e4-957e-51cce93f9fb9.png)

The API has some sorting and pagination support for things like `issues`, but I'm having a hard time getting them to work in an ideal fashion for the releases.

The result of this bug is now `0.4.15` is showing as our latest release, as it is the highest version available on first page of the feed seen here:

https://api.github.com/repos/lmms/lmms/releases

I can append `?page=2` to the URL to temporarily fix this, but I can't figure out how to say `?page=last` or perhaps `?direction=desc`.

**Comment by tresf** [comment]
For now, I've told GitHub to give us the first `1000` results, which temporarily fixes this.

Note, I've also changed the comparison logic per https://github.com/LMMS/lmms.io/commit/7b690615602bcb997262b0a21da9b938f30cab27.  Let me know if this is ok. :)

**Comment by badosu** [comment]
Thanks @tresf!

**Comment by Lukas-W** [comment]
There doesn't seem to be a way to reqeust a sorting other than the default (release date) from GitHub's API. So increasing the page size is the only solution I see. 

> I've also changed the comparison logic to use version comparisons rather than ~~release~~[tag] date comparisons per 7b69061.
 
Should work too :)

**Comment by tresf** [comment]
:+1:
