### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by DeRobyJ** [LMMS/lmms.io#147]
Will the site have different languages?

**Comment by tresf** [comment]
> Will the site have different languages?

Yes, we can add locale support but we have many 3rd party and custom items.  Here's the effort level:
 * **Forums** - Reliant on phpBB [language packs](https://www.phpbb.com/customise/db/translation/italian/) - :+1: `Minimal effort`
* **LSP** - A lot of hard-coded stuff, would need complete rewrite. - :-1: `Large effort`
* **Site Navigation** - Currently relies on English keywords. - :confused: `Moderate effort`
* **Wiki** - Ready to be translated (or have existing translations updated) - :+1:  `Minimal Effort`
* **Base Site** - Would require locale-based templates. - :confused: `Moderate effort`
* **Integrating all locales** -  - :+1: / :-1: - `Unknown effort`

What is disconcerting is that when we have this many 3rd party services our visitors may be forced to define the locale in several places (main site, wiki, forums, lsp, etc) or we as site developers are forced to integrate them (and known which locales to fall back on when a language exists in one area but not another).

What is hopeful is that with the Silex templating engine that Lukas has setup for us, we can tackle the main [site much easier than before](http://www.erikaheidi.com/blog/silex-and-localization-l10n-translationserviceprovider)...

**Comment by tresf** [comment]
So to answer your question... I don't know, it depends on if we have someone ambitious enough to tackle this.

**Comment by DeRobyJ** [comment]
Ok.
In my opinion, only the main site needs translation, and different languages for the phpBB forum are fine too.

(with main site I mean Home and Download pages: these are the most important, as every user has to pass through them and most people decide to download or not by reading the home page)

About the rest of the site, the effort is more than the people reading it.
Also, things like the LSP or the Showcase are easy to read for almost anyone.

**Comment by tresf** [comment]
> with main site I mean Home and Download pages: these are the most important, as every user has to pass through them and most people decide to download or not by reading the home page

Ok, let's open a dedicated bug report for that then. This one is too broad. Furthermore, some assistance would be great.  Our site is 10x more usable than the old one, this isn't a wishing well.
