### ISSUE TITLE
allow attachments to PMs

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms.io#148]
currently we have no attachments on PMs
Threads allows mmpz and wave -is that possible in settings, or does the core not allow it?
-zips would be sufficient

**Comment by Umcaruje** [comment]
PM's where? I don't understand

**Comment by tresf** [comment]
Closed via:

![image](https://cloud.githubusercontent.com/assets/6345473/6287769/2054fe2e-b8e2-11e4-84c3-d9f471c78f34.png)

![image](https://cloud.githubusercontent.com/assets/6345473/6287790/47d6f9de-b8e2-11e4-8985-37f36407e7b1.png)

**Comment by musikBear** [comment]
very nice. it works now
