### ISSUE TITLE
Best Of LMMS Vol 2

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms.io#151]
1. We should probably put the official rules on our home page.
 1. ~~Last years competition should have a link to the new one somewhere in the description.~~(Edit: fixed by Uroš)
 1. We should make the SC URLs similar so people can expect to be able to change the URL to v1, v2, v3 etc. `lmms-top-songs-compilation` is quite different from `the-best-of-lmms-competition-v2`

https://soundcloud.com/groups/lmms-top-songs-compilation

https://soundcloud.com/groups/the-best-of-lmms-competition-v2

@Umcaruje  @sti2nd

**Comment by Sti2nd** [comment]
I think we should link forward to next competition indeed. Maybe it should just be to change the name of the group, Uros? Quote Soundcloud: 
> If you have changed the name of your Group recently and find that the link to your group remains the same please contact us here. And we will be happy to help you fix this from our end.  Please note that this will break all links to your Group using your previous name.

http://help.soundcloud.com/customer/portal/articles/282667 At the bottom

**Comment by tresf** [comment]
It if breaks old links, we may want to hold off until this competition has finished (aprilish).

-Tres

**Comment by tresf** [comment]
Also, unrelated but this allows us to rename munyajumo's old SoundCloud group if we like.

**Comment by Sti2nd** [comment]
> It if breaks old links

ok, but we are going to change the old group link?

**Comment by tresf** [comment]
> ok, but we are going to change the old (last year) group link?

I would be a nice clean-up effort after this years comp is done IMO (if SC allows it) but it's a bit off topic, so no need beating it up.

-Tres

**Comment by Umcaruje** [comment]
I vote we change the group link of the 1st comp when the current one is over. 

Where would the BoL info page go? Maybe as a entry to the community submenu? Or a seperate entry in the navbar?

**Comment by tresf** [comment]
I'm not sure... It is going to be a temporary thing so perhaps we could put a banner on the front page about it and have a dedicated page (lmms.io/competitions).  Under community would probably be appropriate, but we can also cross-link from the featured page and the get-involved page if we think people might navigate through those means?

**Comment by Umcaruje** [comment]
>we can also cross-link from the featured page and the get-involved page if we think people might navigate through those means?

Sounds like a plan. 

I'll throw a pull request for the new page, when I get some free time to make it

**Comment by tresf** [comment]
:+1: terrific!
