### ISSUE TITLE
404 on sample download link

### ISSUE THREAD

**Issue by kpfries** [LMMS/lmms.io#153]
http://lmms.io/download/samples on the github samples page throws a 404 my way.

**Comment by Lukas-W** [comment]
Thanks for your report. The sample page was removed, see #140. Where did you get that link from?

**Comment by Umcaruje** [comment]
I guess its the `LMMS/Samples` repo's Readme. I changed it via https://github.com/LMMS/Samples/commit/3ab4b87c88ca7c5f74c25cfcd8c63f09efa3009a. 

Should this be closed as a wontfix? There will be no 404 when there is a page there ;)

**Comment by tresf** [comment]
Well, technically fixed since you found the bad link. :+1:
