### ISSUE TITLE
massive spam attack - banning does not remove posts

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms.io#155]
Had to happen :/
From 
04 Apr 2015, 11:46
to
04 Apr 2015, 16:36
90+ spambots has joined the forum, and posted 5 identical topics
I have banned a handful, but adding them to the ban-list, does *not remove* their posts :/
Are there any 'smart' way to ban **and** cascade remove **all** posts of these attackers in one go? -Or is that only possible with a script on the server?
**We need capcha as part of  joining the community**

**Comment by tresf** [comment]
Yes, the admin area of the forums has a place to delete all posts as part of the banning process.  I'll do some cleanup.

> We need capcha as part of joining the community

We have it. (technically reCapcha)  Probably something else happening.

**Comment by tresf** [comment]
For phpBB admins:

1. Browse forum with spam, click `username`
 ![screen shot 2015-04-04 at 11 09 49 am](https://cloud.githubusercontent.com/assets/6345473/6993228/ae06d486-dabb-11e4-8f7a-1a7f16509409.png)

2. At top of profile, click `Administer user`
 ![screen shot 2015-04-04 at 11 10 47 am](https://cloud.githubusercontent.com/assets/6345473/6993229/ae071e1e-dabb-11e4-9ae7-693130e35537.png)

3. Scroll to bottom of page, click `delete posts` in the delete user area, click `Submit`.
 ![screen shot 2015-04-04 at 11 11 42 am](https://cloud.githubusercontent.com/assets/6345473/6993227/ae05f9a8-dabb-11e4-88e2-99ff7a966def.png)

**Comment by musikBear** [comment]
I only see
Username: feelingera06525 [ Banning ] 
No [administer user|

**Comment by tresf** [comment]
You must not be a forum administrator (just a moderator)

**Comment by Umcaruje** [comment]
I'm deleting them all of the accounts and IP banning them. Thanks for the report @musikBear

**Comment by musikBear** [comment]
@Umcaruje goodie - wonder how they got past chapta ... :/
@tresf different 'class' .. i understand :p

**Comment by Umcaruje** [comment]
Deleted all the spammers using the 'Prune Users' feature in ACP

Deleted all users that joined after april 4th. 

Double checked if there were some real people there, but there weren't.

**Comment by tresf** [comment]
@Umcaruje great work, thanks, although we may lose the ability to see the IP addresses now.  I've banned most of the IPs, but the spammer seemed to use a range and I was going through one by one.

**Comment by tresf** [comment]
Just saw the part about you banning IPs too.  Looks like we were both working on the same issue. :+1:

**Comment by Umcaruje** [comment]
:+1:

**Comment by musikBear** [comment]
@Umcaruje  @tresf  Guys.. he is back :/
How does 'he' get pass the chapta ?

**Comment by Umcaruje** [comment]
no idea

**Comment by Umcaruje** [comment]
deleted the acc

**Comment by musikBear** [comment]
If you can add me, i will help of cause - There is a new small attack here monday

**Comment by musikBear** [comment]
@Umcaruje - will you post a heads-up on face-book about the maintenance 7-9 apr? I think a lot of users wont see the thread in forum, because it simple is buried under +300 spam pieces..

**Comment by Umcaruje** [comment]
@musikBear when I do the maintenance I'll implement more spam filters ( #2 ).

The thread is global and it will appear over all posts, so no need to write a FB post tbh.

**Comment by Umcaruje** [comment]
The account registration is on manual mode now, which means all new accounts have to be approved by admins. This is just an interim solution to the spam problem.

**Comment by tresf** [comment]
Ok.  I just deleted a bunch that came in.  Hopefully this update to the new phpBB offers us more in terms of preventing this stuff...

**Comment by musikBear** [comment]
If this administrator approval is still in action, then the forum has been hacked for real!
Spam arrives as i write this- The user subscribed TODAY!
How is that possible? 
I cant do anything, but report it to you @tresf @Umcaruje 
B.r.

**Comment by tresf** [comment]
I've cleaned them up for now.

**Comment by musikBear** [comment]
woow! that was fast :dancer:

**Comment by Umcaruje** [comment]
I turned the registations back on to test up a anti-spam plugin. Guess it doesen't work as good as they advertise it

**Comment by Umcaruje** [comment]
Ok, I installed a new sortables captcha which looks like this:
![image](https://cloud.githubusercontent.com/assets/6282045/7145707/948897c0-e2ee-11e4-82f8-3d43501d9231.png)

I think this should hold the spammers off

**Comment by Umcaruje** [comment]
Oh and @tresf @musikBear Its pointless to ban the IP for this spammer, since he most probably uses tor and some IP reset script. I think its better to ban emails, since he seems to reuse them.

**Comment by musikBear** [comment]
sad to tell, that right now, spams are arriving 
Is this jerk dumb enough to actually create handmade accounts ?!
I cant believe he got pass @Umcaruje latest effort
How ? if not manually creating real accounts 
Then WHY  !?  ://

**Comment by tresf** [comment]
It is likely because phpBB stinks in this regard.  Captcha only helps if it is a firewall before the php pages that actually register.  This is why @eagles051387 recommended another plugin which AFAIK obfuscated the registration URL, but he never implemented it for us.

**Comment by Umcaruje** [comment]
Well there were only 2 spam accounts since I added the new captcha. I'll soon set up that newly registered accounts (ones under 2-3 posts) can't post without a moderator approval. That should bring our spammer friend down.

**Comment by tresf** [comment]
>  I'll soon set up that newly registered accounts (ones under 2-3 posts) can't post without a moderator approval. That should bring our spammer friend down.

Please do not.  We want to know when accounts are getting created, and if we moderate them, we'll have hundreds of accounts that we won't even know exist.  If we fix this, we shouldn't do it reactively, we shouldn't punish those trying to use our boards.

**Comment by Umcaruje** [comment]
>and if we moderate them, we'll have hundreds of accounts that we won't even know exist.

But any admin/moderator will get a notification when there is a new post that needs approval. If we just approve the first ever post of a user, that can be really reasonable in terms of preventing spam.

**Comment by tresf** [comment]
People usually register so they can post and you're stopping them mid-thought.  It's a terrible idea always. We want to steer people to our forums for questions.  If we make it more difficult than it already is, they'll flock to facebook and GitHub and then we'll just have more Reaper10's making dozens of bug reports just to get a conversation started.  Please don't do this. :)

**Comment by musikBear** [comment]
agrees with tresf. it will be annoying not to be able to post, right after signing-up. However some forums has a '*you now only have to click in a link in the mail we just send to you*' 
Eg the user has to make a second active **human** response, before the account *is active*. Does that kind of option exists in phpBB ?

**Comment by tresf** [comment]
> However some forums has a 'you now only have to click in a link in the mail we just send to you' 
Eg the user has to make a second active human response, before the account is active. Does that kind of option exists in phpBB ?

Yes and it is enabled.

**Comment by Umcaruje** [comment]
>agrees with tresf. it will be annoying not to be able to post, right after signing-up. However some forums has a 'you now only have to click in a link in the mail we just send to you' 
Eg the user has to make a second active human response, before the account is active. Does that kind of option exists in phpBB ?

Yeah that is enabled on our forums, but almost every spambot is 'smart' enough to check its inbox and activate the account...

**Comment by musikBear** [comment]
>  but almost every spambot is 'smart' enough to check its inbox and activate the account...

Oo .. :cactus:

**Comment by Umcaruje** [comment]
I think this issue can be closed. The new captcha does its job well and there is maybe 1 or 2 spambots that get through. We can easily handle that by blocking emails and deleting the users and their posts.

@musikBear @tresf if you feel that this issue wasn't fixed, please reopen.
