### ISSUE TITLE
LSP file name shouldn't be in parentheses

### ISSUE THREAD

**Issue by Umcaruje** [LMMS/lmms.io#156]
![image](https://cloud.githubusercontent.com/assets/6282045/7241601/a550b9ae-e7ba-11e4-9186-ff152564cccf.png)

Shouldn't be too hard to fix.

**Comment by tresf** [comment]
![image](https://cloud.githubusercontent.com/assets/6345473/13884090/b88cf11a-ed02-11e5-8932-89deea34acab.png)
