### ISSUE TITLE
Tutorial for Vocoder-Type FX Plugins

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms.io#157]
Per: https://github.com/LMMS/lmms/issues/2003#issuecomment-95632359

This should be added to our wiki:

> The way to use it is not-too-complicated (but, yes, it is a tweak as  LMMS is not designed for that kind of things):
>  1. create a track with (let say) an audio file of your voice
>     a. put its pan to full left
>     b. assign it to a FX channel
>  2. create a track with instruments
>     a. put its pan to full right
>     b. assign it to the same FX channel
>  3. add "Vocoder for LMMS" plugin to this FX channel
> 
>  -> play.
>  I planed to submit a HOW-TO for this plugin for the users' wiki but  still not get the time to do it.
> 
> Regards, Y.

**Comment by musikBear** [comment]
done

**Comment by Umcaruje** [comment]
Closed via http://lmms.io/wiki/index.php?title=Working_with_LADSPA_effects#Vocoder

**Comment by tresf** [comment]
Ok, but FYI this applies to native, VST and LADSPA, so the LADSPA title is misleadingly specific in this context.
