### ISSUE TITLE
Chime in tresf !

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms.io#158]
Have you ok'ed the response in forum:
'3286'
Like to talk on 'skype'
click here https://appear.in/lmmstalk

**Comment by Umcaruje** [comment]
Could you please be more clear, what is this issue about?

**Comment by musikBear** [comment]
i  prefer not say other than '3286'
But couldent you use the link i gave and i will tell you.
This is best suited for a voice chat

**Comment by tresf** [comment]
>  prefer not say other than '3286'

Then don't use a public tracker.

> But couldent you use the link i gave and i will tell you.

Don't be pretentious, this is a public tracker and we're also a public community.  If you want help with something LMMS related, there's a 99.9% chance @Umcaruje can help.

**Comment by musikBear** [comment]
I dont 'want help'
I have im'ed you related to 3286. This has now a new angle
I obvious do not want it on public tracker. It does not belong there
@Umcaruje did understand, but have no real solution, and are perhaps not as paranoid as i am..
Sometimes paranoia is a good thing.
but im here for an hour or so
https://appear.in/lmmstalk

**Comment by tresf** [comment]
Uros' judgement is perfectly fine.  If you need to PM me, I can be reached on Google Hangouts or I'll sign into another service.  Forums aren't a good medium for me and I'm not going to use voice chat as I feel that is preposterous.

**Comment by musikBear** [comment]
ok
understood. You have seen the pm i send you from forum, regarding this situation?
 and you cant see any problems at all?
Then im alone with my paranoia, but thats ok
Have a nice day. :)

**Comment by tresf** [comment]
> You have seen the pm i send you from forum, regarding this situation?

Stop being vague.  I just told you I'm not using the forums for PM and the next question is "have you read your PM".

**Comment by musikBear** [comment]
i send you a pm several days ago, when the issue came up, and you answered in a defensive way, not addressing the question at all. After that stakeout opened a potential problem. What exactly should i do? I dont have an account for google circles, in fact i know nothing about it. Must say that it is a bit strange not to accept im's from forum. But i have done everything i can now, and @Umcaruje has listen to me, and there is where things are. I will not repeat my im in open forum, cause that could be harmful
I cant do more. Just hope that this is not a problem
Please talk to Umcaruje

**Comment by tresf** [comment]
> I dont have an account for google circles, in fact i know nothing about it

I frankly don't give a shit what you do or don't know about.  If you have problems with Google, say that, but don't hide behind ignorance.  You are asking for help and I'm saying to choose a different medium than the forums.

**Comment by tresf** [comment]
Ok, I read your PM. You're asking about sample licensing.  We have a samples repo as well as an ongoing public discussion about that.  Please use the resources we already have.

**Comment by tresf** [comment]
I'd like to elaborate a bit more on this topic... 

@musikBear's concern is best described here:

> LMMS is getting a position in the daw-world. Perhaps to a degree, where someone would like to deal it a punch
This could be such a case!
Eg a trap

Besides being very difficult to read, what I sense here is a bit of paranoia about our project being "trapped" into something, possibly related to invalid sample licensing?

But I'm not sure what the concern is.  If there is an issue with the samples, we should address them.  If people inquire about licensing, we tell them what we know and move on.  Most of the time they just need to read the licensing.  If we don't know the licensing, we tell them we "don't know" and if we're doing thing right, we mark them for removal in our project (something we've asked for help on many times over and received very little).

**Comment by musikBear** [comment]
> (something we've asked for help on many times over and received very little help with).

Another quote from my IM
> :..when all that mehe happend with the sample-lib-update.
(what a sad thing, that was.. I still think we should try a new approach to the generous creators, that already was contacted, there just have to be better internal agreements, before any kind of new contacts are made - If you find it could be beneficial, i can write a proposal for discussion

Help offered -again
Help rejected.

**Comment by Umcaruje** [comment]
I think that this is something to keep an eye on, but not something to panic about. Removing posts or making up excuses for the not properly licensed samples is a bad thing to do imo. 

Yes, mistakes were made and we don't have a clue where our current samples come from, but we have an ongoing effort for replacing the samples that will probably take place with LMMS 2.0. There is no need to panic.

**Comment by tresf** [comment]
> Help offered -again. Help rejected.

If you want to help with either cleaning up our current samples or with the samples repo, just get in there and do it.
