### ISSUE TITLE
Login to edit in wiki fails for some

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms.io#159]
This guy 
http://lmms.io/forum/memberlist.php?mode=viewprofile&u=1882
says  
> i'm dying to update the vst section of the wiki but i don't know what to do after signing up for the mailing list

I send him the link for login, but that did not work for him.
Is there a problem? Has he at all signed up for wiki?
(my login works)

**Comment by Umcaruje** [comment]
Closing as invalid, since not enough information has been provided. If you think I made a mistake, please reopen.
