### ISSUE TITLE
[wiki] better section for sound-devices

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms.io#162]
I dont know enough to write this, but someone who does, should explain what **additional settings** 
in this sub-window: 
https://lmms.io/documentation/LMMS_Settings#Audio_Settings
can do, and why/ when they should be used.
Eg: What can be inserted in the field for *'DEVICE'*
I only have 'SDL' and nothing else in my windows device-settings, but perhaps i could get better sound ..i dont know, and we have no explanations in wiki, at all..
Who can explain it, and write it?

**Comment by tresf** [comment]
> **lmms.io wiki:** With each interface, you can select the actual device and the number of channels used by LMMS. These are interface-dependent settings and should be left at their defaults unless you have a good understanding of the interface in use on your computer.

I'm not sure this could be more clear.  What part do you need explained?

**Comment by musikBear** [comment]
As i already wrote
>*What can be inserted in the field for 'DEVICE'*
Its not a select-box, the user need to write 'something' or nothing, but when to do what, and what options exists for SDL, Direct-sound, jack, alsa .. asio ?
What is the field **for**
There is nothing about this setting in the wiki at all

**Comment by tresf** [comment]
> There is nothing about this setting in the wiki at all

Should there be?  It is for advanced users.  If you know more about SDL, change it.  Should it be our responsibility to explain the SDL advanced settings (and all back-ends for that matter?)

If you discover something you'd feel is worth adding, please do, but to blindly open a bug report for advanced settings that explicitly say **"should be left at their defaults unless you have a good understanding of the interface in use on your computer."** seems like a blind request. :)

**Comment by tresf** [comment]
Stale and abandoned.  Closing.
