### ISSUE TITLE
Case-sensitivity of LSP usernames

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms.io#164]
reported in forum
http://lmms.io/forum/viewtopic.php?f=7&t=3397
apparently users **can** login with wrong case-log-name, but can **not act** as user
They should ofcause **not** be able to log in at all, if the case is wrong in the username
OR
case should not matter at all **in user-NAME** ofcause it must in password

**Comment by Umcaruje** [comment]
Yeah, confirmed, I can log into my account when I use different case for my username, but can't edit my sounds.

**Comment by tresf** [comment]
Probably just decline the login here if it doesn't match.  Otherwise, you'd have to look up the case sensitive version of the login in the database and reset it using `set_get_post(...)`.

https://github.com/LMMS/lmms.io/blob/master/public/lsp/utils.php#L359
