### ISSUE TITLE
Less rigid file limitation on LSP

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms.io#165]
a forum user like to share a whole Synth1-bank
He linked to his own drive and thats fine, right *now*, but i thought it would be good if it was on LSP. That is not possible, Restrictions are so rigid, that neither rar nor zip are allowed.
Of cause its necessary to protect LSP against vira and other problems, but a balance between security and usability should be reachable   
Synth1 banks are btw simple folders, -those can never be up loadable, so they need to be compressed to rar / zip

**Comment by tresf** [comment]
> Restrictions are so rigid, that neither rar nor zip are allowed.

And they never will be.

> Synth1 banks are btw simple folders, -those can never be up loadable, so they need to be compressed to rar / zip

Then it's a bad format for sharing. Come up with an actual solution rather than criticizing it please.  We won't allow RARs.  We won't allow ZIPs.

-Tres

**Comment by tresf** [comment]
I'd like to add, that if a bank file isn't currently up-loadable we can add the extension to LSP, but the bundling is a separate topic. We need better bundling capabilities in LMMS period and the LSP isn't the place to vent about that.

**Comment by tresf** [comment]
> And they never will be.
