### ISSUE TITLE
LSP password reset functionality

### ISSUE THREAD

**Issue by Fastigium** [LMMS/lmms.io#167]
So I forgot my password for the LSP, tried a few guesses to no avail, had a look at the source code and realized I had locked myself out of my account irrevocably. As far as I can see, there is no password reset functionality and no way to reset the loginFailureCount, barring direct intervention in the database. This strikes me as suboptimal. A password reset mechanism is common and expected functionality these days.

However, most password reset mechanisms rely on email verification. This is a bit of a problem with the LSP, as it only stores a username and real name (both of which are public) and a password, which is usually forgotten in case a reset is needed. It seems unfeasible to automatically verify a password reset request without knowing additional information, like an email address or a secret question/answer.

Adding a fully automatic password reset mechanism would therefore involve adding an additional field to the user table and, possibly, collecting information for that field for existing accounts (e.g. using some kind of notification at the next login). The ratio between the amount of work required for this and how often it will be used is unknown to me, however. An alternative would be to add a "Forgot password" page with a way to contact a person with database access. Verification might then be done manually, for example by exchanging a message with a known email address or Soundcloud account.

The purpose of this issue is, in order of ascending importance to my own case, to
1. initiate a discussion about the desirability and possible implementation of password reset functionality for the LSP, and
2. get my account back :grin:. I'll be happy to verify I'm me using my email address or my Soundcloud account. If possible, I'd love to have the SHA1sum of my old password, just to see what in screaming blue heck I was thinking when I set it.

**Comment by tresf** [comment]
Your `loginFailureCount` is currently `0`.  Are you typing it in with a capital `F` per #164?

In regards to better password management, agreed.  I personally would like to just use the phpBB forum session and have the login to one allow access to the other, but haven't put the time into it.  phpBB also allows 3rd party authentication providers too.  There's nothing stopping this development except someone who doesn't mind digging into the LSP code.  There haven't been too many people to work on the codebase so far, but if you are interested, we can send you a copy of the database.

**Comment by tresf** [comment]
Also, if you want your password hash, just shoot us your gmail address and we'll happily send it over.

**Comment by Fastigium** [comment]
Yay, let me have it at fastigiummusic@gmail.com :). As for the loginFailureCount being 0: strange, I tried a lot of wrong passwords. Is there a cron job or something resetting that count every once in a while?

**Comment by tresf** [comment]
> Is there a cron job or something resetting that count every once in a while?

More likely that it is simply broken. :+1:  Hash sent.

**Comment by Fastigium** [comment]
Thanks, time to get crackin' :)! For the record: yes, I tried with a capital 'F', and no, sorry, I don't have the spare time/energy right now to assist with large code updates. Thanks for the quick reply!

**Comment by tresf** [comment]
Actually I take that back... is there a chance you're logging in properly and resetting it to zero?  We have some strange issues with browsers from time to time and the page breaks.  Not sure why, but you might want to try another browser and see if you actually have it right and the symptom is misleading.

**Comment by Fastigium** [comment]
After trying some manual entries while the cracker is running, I think I can safely say I haven't accidentally tried the right password. So no browser issues, just plain forgotten password. My memory is stirring a bit, maybe it'll beat the cracker after all ;).

**Comment by tresf** [comment]
You sound like you're having fun, but we can reset it too if you'd like. :+1:

**Comment by Fastigium** [comment]
Yes, that is probably best. Even at 131 million hashes per second, it still takes over 7 hours to brute-force all passwords of length 7, and that only includes alphanumerical characters :grin:. If you could set a new password and email it to me, I'll change it into something else and remember it this time!

**Comment by tresf** [comment]
Sent.

**Comment by Fastigium** [comment]
Thanks!

**Comment by kmklr72** [comment]
I think Fastigium's idea of a notification after login would be easier in the short term but I do like the notion of an integration with phpBB.

If I may ask, what was the reasoning behind not storing email addresses originally? I would think making it a registration requirement would be beneficial not only for this, but future uses as well (e.g. user notifications). In any case, I'd like to take a crack at this if no one else wants to.

@tresf Could you send me a copy of the database? My email is kmklr72@gmail.com

**Comment by tresf** [comment]
> If I may ask, what was the reasoning behind not storing email addresses originally? I would think making it a registration requirement would be beneficial not only for this, but future uses as well (e.g. user notifications). In any case, I'd like to take a crack at this if no one else wants to.

Impossible to say as the decision was made by Toby a long time ago.

> @tresf Could you send me a copy of the database? My email is kmklr72@gmail.com

For security reasons (and the fact that I don't know you), I would have to scrub all of the hashes before sending.  Is that ok?

-Tres

**Comment by kmklr72** [comment]
Definitely. All I really need is the structure so you can just send that if you wanted to save on the space. I can always generate dummy data if I need it.

**Comment by tresf** [comment]
Sent.  The only data in there that is confidential is the users, so that's all I've stripped out.  The file is 1.1 MB gzip compressed.

If you find anything in there that you find confidential that I had missed, please treat it as such.  Thanks for taking a look!

-Tres

**Comment by tresf** [comment]
Well, we can't reset passwords if we have no challenge info and no email stored, so this is a moot point (garbage input yields garbage output).

Since @kmklr72 never started work on this and we need a better LSP anyway, this is really just a topic about an LSP rewrite, thus has no purpose remaining open.  Whatever system we replace LSP with, it will have a password management feature. :+1:
