### ISSUE TITLE
forum is down

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms.io#168]
apparently something is gone wrong in forum:
![forumdown](https://cloud.githubusercontent.com/assets/6662066/9580371/5b90be16-4ff9-11e5-8c2c-1649792a7c4e.jpg)

**Comment by tresf** [comment]
Down?  No.  Ugly? Perhaps.

Chances are @Umcaruje is working on an upgrade to our bootstrap theme (discussed in the tracker).  I'll let him chime in.

**Comment by tresf** [comment]
Duplicate of #114

**Comment by musikBear** [comment]
okidoki -did not see a topic about an upgrade
Looks different now, but it works
Is a tiny message to users needed?

**Comment by tresf** [comment]
> Is a tiny message to users needed?


We've had a phpbb logo there for months, I'd say no.  If you want to ressurect an old announcement, feel free, please don't pin it tho as uros plans to finish it soon.
