### ISSUE TITLE
Wiki error on thumbnails

### ISSUE THREAD

**Issue by Sti2nd** [LMMS/lmms.io#169]
https://lmms.io/documentation/Manual
https://lmms.io/documentation/Plugins

I couldn't find if this has been reported.

**Comment by Umcaruje** [comment]
huh maybe that's that inodes problem that caused the forums instability too.

The wiki page looks fine: http://lmms.io/wiki/index.php?title=Manual

@Lukas-W @tresf is there a way to make a global recaching of the documentation pages?

**Comment by tresf** [comment]
Fixed via 

```bash
sudo rm -rf /tmp/wiki
```
