### ISSUE TITLE
Banning and deleting manual several hundreds spam topics 

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms.io#170]
Right now the forum is drowned in spam.
I have banned the user, and started to delete the spam.
So i made a mistake and deleted one topic that should not be deleted 
I can find the topic * 'Introduce yourself here' ** on page 10 of the deleted topics, but there is no topics in the moderator-Que at all. Why is that?
I am not even halfway through all this spam, but now i need coffee 

I btw cant understand why there is no option for deleting all posts of a banned user, in one simple operation -If there is a 'higher-level' of moderation. I apply :p

**Comment by tresf** [comment]
> I btw cant understand why there is no option for deleting all posts of a banned user, in one simple operation -If there is a 'higher-level' of moderation. I apply :p

There is, but you have to be an administrator to use it... 

 * Administration Control Panel
 * Manage Users
 * Paste `jdfgdfgrr` into user id, Submit
 * Ban by IP address via "Basic Tools", "Quick Tools", "Ban IP"
 * Scroll to bottom of page, under "Delete User" click "Delete Posts"

**Comment by musikBear** [comment]
ok, i only have moderator privileged. I guess this +500 topics (bot made ofcause) then need to be fixed by @Umcaruje. Why the list of deleted topics is empty, i cant understand, but i cant fix my mistake. The pinned topic 'Introduce yourself Here' also need Umcaruje -sorry about that

**Comment by tresf** [comment]
> So i made a mistake and deleted one topic that should not be deleted 

Restoring a topic is quite a bit of work and requires a modern backup of the database.  I'm not sure this is worth our time for an "introduce yourself" thread and frankly, I'm not going to spend the next 2 hours fixing this mistake that you made.

> If there is a 'higher-level' of moderation. I apply :p

We can add you as an administrator, but these types of mistakes cost hours of our time, so we need to first be comfortable with the level of caution taken when using these features.

**Comment by tresf** [comment]
> ok, i only have moderator privileged. I guess this +500 topics (bot made ofcause) then need to be fixed by @Umcaruje. Why the list of deleted topics is empty, i cant understand, but i cant fix my mistake. The pinned topic 'Introduce yourself Here' also need Umcaruje -sorry about that

I had forgot to mention that I have already deleted this user and banned the IP address, so that should be all set. If there are other users spamming our forum that require banning or bulk thread deletion, please continue to escalate as you have today.

In the mean time if someone wants to take the time to restore the deleted thread, feel free to open a new issue and track it there.

**Comment by tresf** [comment]
And last but not least, thanks for continuing to monitor our forums and raise these issues to our attention.  It is greatly appreciated. :+1:

**Comment by musikBear** [comment]
I'm just happy to assist the project, that i love. 
Sorry for the inconvenience with the deleted topic, once more.

**Comment by tresf** [comment]
FYI, Added bulk deletion procedure here:  https://github.com/LMMS/lmms.io/wiki/Forums-Bulk-Deletion-of-Posts

**Comment by musikBear** [comment]
There was one also today *laraaakim11*, but there was only some few pages, so it was no problem. I banned him too.
