### ISSUE TITLE
The document tab on the LMMS main site throws an error 500.

### ISSUE THREAD

**Issue by shadow7412** [LMMS/lmms.io#171]

**Comment by tresf** [comment]
@shadow7412 thanks, we'll take a look.  In the mean time, you can access the documentation via https://lmms.io/wiki/.

@Lukas-W, FYI.

**Comment by shadow7412** [comment]
Ah nice. Thanks for the link.

**Comment by tresf** [comment]
It appears cURL is throwing the following error (which is suppressed by something which catches and displays errors somewhere along the lines)

```
CURLE_SSL_CACERT (60)
Peer certificate cannot be authenticated with known CA certificates.
```

This suggests the server is having a hard time verifying its own HTTPS certificate.... investigating...

**Comment by tresf** [comment]
Patched via 27fb49e, so this will work for now.  I've emailed the hosting provider to see if there is a misconfiguration with our SSL certificate.

**Comment by tresf** [comment]
This should be fixed.  Copy of email below.

> Hi Tres,
> 
> We have resolved the issue. Please check it and let's know incase you need any further assistance from our side.
> 
> You can now verify the same through : https://www.sslshopper.com/ssl-checker.html#hostname=www.lmms.io
> 
> 
> Thank You,
> [Hosting Support]

**Comment by shadow7412** [comment]
Confirmed - it's working now.
