### ISSUE TITLE
lmms.io link to PDF manual is broken

### ISSUE THREAD

**Issue by jamshark70** [LMMS/lmms.io#172]
At https://lmms.io/documentation/ the link `[pdf] (for v0.4.12)` points to https://sourceforge.net/projects/lmms/files/UserManual/

On this page, there are no files available for download.

At least remove a link which is no longer maintained.

(As a side note, lmms.io's reliance on google APIs means that it is very nearly unusable behind the Great Firewall of China. I wanted to download a PDF manual so that I would not have to wait 30-60 seconds for every page load.)

**Comment by tresf** [comment]
> At https://lmms.io/documentation/ the link [pdf] (for v0.4.12) points to https://sourceforge.net/projects/lmms/files/UserManual/

> On this page, there are no files available for download.

> At least remove a link which is no longer maintained.

Closed via https://github.com/LMMS/lmms.io/commit/8d2643343ff31bfc1df310705076d53285785cdb.  Please use this direct link or use the updated link from the wiki  https://lmms.io/pdf/lmms-manual-0.4.12.pdf

P.S. Thanks @Umcaruje for fixing the wiki side.


> lmms.io's reliance on google APIs means that it is very nearly unusable behind the Great Firewall of China.

We use Google for fonts and jQuery.  Ironically, we use hosted versions for **faster** page loading (CDN, etc) but this seems to be having an adverse affect for you.

We can certainly move those files to our own hosting if it helps page loads for people connecting from China.

In regards to "Google APIs", we use the standard Google Analytics API, which we use to help measure page hits.

But before we make any changes we need help... 

 1. Please open a dedicated bug report for slow page loads
 2. Of these 3 JavaScript resources, can you please identify which one(s) are causing the slow load times?
 3. In your new bug report please offer any China-firewall-simulation proxy services we can use to test compatibility.
