### ISSUE TITLE
official linux downloads point to 1.0.0

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms.io#174]
Here 
http://lmms.io/forum/viewtopic.php?f=7&t=4731
a user claims that the dl for linux 
on the offocial dl page https://lmms.io/download/#linux is version 1.0.0. 

Is that true, or is it only the version stamp that is wrong?
He btw also have problems that i cant solve

**Comment by tresf** [comment]
We don't distribute a Linux version, but rather link to other people that do.
