### ISSUE TITLE
Forum uses ComBoot favicon

### ISSUE THREAD

**Issue by softrabbit** [LMMS/lmms.io#175]
Wouldn't the LMMS logo icon be more suitable for the forum?

Update before someone closes this as invalid: looks like they both are in the code, Firefox shows the ComBoot icon while Chrome shows the LMMS logo icon.

**Comment by Umcaruje** [comment]
> looks like they both are in the code
I'll look into this

**Comment by Umcaruje** [comment]
@softrabbit could you check out if this is fixed?

**Comment by softrabbit** [comment]
Yeah, fixed.
