### ISSUE TITLE
Misleading installation instructions in the wiki

### ISSUE THREAD

**Issue by DeRobyJ** [LMMS/lmms.io#178]
I just saw that German and Italian documentation for installation are really outdated and misleading.

I decided to do the Italian translation of the lmms.io/download page.
The English page has been deleted long ago, but German and French ones are still there.
The French one is actually still in English.

I'm marking the German one as Outdated, so if there are German speakers please chime in.

**Comment by tresf** [comment]
> I decided to do the Italian translation of the lmms.io/download page.

Thanks.  Note, this statement can be quite misleading as we actually have an `lmms.io/download` page as part of our public source code repository.

If you can, link directly to the wiki articles you're speaking about so that other wiki maintainers are aware of what you're describing.

**Comment by DeRobyJ** [comment]
Ok

From the mediawiki instance:
https://lmms.io/wiki/index.php?title=De:Installation
https://lmms.io/wiki/index.php?title=Fr:Installation

**Comment by tresf** [comment]
Those aren't installation instructions really, they're simply build instructions.  I'm not sure how much value they even have being on the wiki, we have great build tutorials on our GitHub page for building (and we should do better Linux packaging to avoid such a mess in the first place).

**Comment by DeRobyJ** [comment]
That's right. That's why I decided to do something different with the Italian one.
First: some general information about Windows, OSX and Deb via package manager.

Then, the commands devided for distros (with information about KXStudio repository)
Just the same as the download page.

https://lmms.io/wiki/index.php?title=It:Installazione

**Comment by tresf** [comment]
> That's right. That's why I decided to do something different with the Italian one.
First: some general information about Windows, OSX and Deb via package manager.

But why?  You're putting our dev documentation in an area already covered perfectly fine on our downloads page.

Instead, local support for our downloads page would put this information where it is useful, not buried in a wiki somewhere.

**Comment by DeRobyJ** [comment]
OK, when the localization system of the download page will be ready I will traslate it. I asked for it a year ago, and during this year Italian users had no informations but if they read English.

I thought that a user going to the italian wiki and clicking on "Installation" would prefer info in Italian over a redirection to the download page!

**Comment by tresf** [comment]
>  I asked for it a year ago, and during this year Italian users had no informations but if they read English.

Excuse me?  This isn't a request forum.  I have a few problems with this whole process... let me identify them... 

1. The wiki's German translation is 50% English, so you can piss off with that comment.
2. The wiki's French translation is 100% English.
3. The new version of the wiki's Italian translation is just a copy from our downloads page with a few words translated.  Linux users can figure this out.  These instructions aren't filled with long paragraphs of content that would leave a user lost.
4.  Google Chrome offers automatic translation for pages which aren't in a native language, which is often "good enough" until proper locale is rolled out.  Perhaps your time is better spent fixing our existing HTML to work better with a canned translation service such as Google's.

Again, delete the pages and point any links to https://lmms.io/downloads

In the mean time, if you want to help provide translation support for our Downloads page, please do.

**Comment by DeRobyJ** [comment]
I'm not requesting, I'm just stating that there is that. Sorry if it sounded different.

Ok then, I'm deleting that.
