### ISSUE TITLE
Useful Resources... 404 (dead external links on wiki page)

### ISSUE THREAD

**Issue by DeRobyJ** [LMMS/lmms.io#179]
This page in the wiki https://lmms.io/wiki/index.php?title=Useful_resources would be really cool... but it's kinda outdated...

So, before deleting or replacing links, I wanted to ask you if there is some that moved to other domains or things like that. Or if you want to include more.

Dead links:
http://www.homemusician.net/
http://www.brycecoulson.com/samples/
http://www.samples-share.com/ (I think...)
http://www.hammersound.net/

I actually have some resources to propose:

http://free-sample-packs.com/
should be royality free

http://www.grsites.com/archive/sounds/
noises and FX, Commercial

http://soundbible.com/royalty-free-sounds-1.html
noises and FX, royality free

http://www.fruitytuts.com/Downloads/
should be royality free

http://howtomakeelectronicmusic.com/ 
tutorials and tips (based on flstudio tho)

http://bedroomproducersblog.com/
blog, review software and writes about discounts

http://machines.hyperreal.org/samples.html 
classic drum-machines and synth sounds

http://www.musicradar.com/news/tech/free-music-samples-download-loops-hits-and-multis-627820
should be royality free

And then some programs:
First, I think we should include audacityteam.org/

Then, the complete version of sfxr 
http://www.drpetter.se/project_sfxr.html
and the web-based one (since the original is not built for osx)
http://www.bfxr.net/
Do you think it makes a point to link them, even tho we have the embedded one?

And then these two, but they are for Windows only and must be tested at least on wine before linking them...

https://xenakios.wordpress.com/downloads/   <- a pretty cool one, granular synth
http://hypermammut.sourceforge.net/paulstretch/ <- sound stretching, also kinda granular

Any thoughts on these?

**Comment by Umcaruje** [comment]
Just add them to the wiki page, you can edit them.

**Comment by DeRobyJ** [comment]
Oh fine.
About windows only programs?

**Comment by Umcaruje** [comment]
paulstretch is a part of audacity, for the other one idk, do as you wish :)

**Comment by tresf** [comment]
> Just add them to the wiki page, you can edit them.

We don't need a bug report for each wiki update.  As @Umcaruje said, just take care of them, that's fine! :+1:
