### ISSUE TITLE
Waveform descriptions in Wiki

### ISSUE THREAD

**Issue by Spekular** [LMMS/lmms.io#182]
The [SFXR](https://lmms.io/wiki/index.php?title=SFXR) page currently describes square, saw, sine, and noise waveforms. While useful to a beginner, this information might be better suited on a separate page, another website, or left out.

**Comment by tresf** [comment]
Please edit to provide a link to the offending article as well as a proposal as to how to fix this if it's not removed/left out.

For example, if all references to "Saw, Sine and Noise" can be on a dedicated waveform page, let's get that created and get this closed out.  The wiki is as good as its maintainers and we can and should be in the habit of fixing those items which we feel need fixing. :+1:

**Comment by Spekular** [comment]
@tresf [offending article](https://lmms.io/wiki/index.php?title=SFXR)

I'm not entirely comfortable making what I consider to be major changes to the wiki without asking for feedback, but I'll go ahead.

**Comment by Spekular** [comment]
@tresf Page added. I've run into an issue though.

Attempting to resize images or create a gallery gives the following error:

    Error creating thumbnail: /bin/bash: /usr/bin/convert: No such file or directory

    Error code: 127

**Comment by tresf** [comment]
> /usr/bin/convert: No such file or directory

Ran:

```bash
sudo apt-get update
sudo apt-get install imagemagick
```

`/usr/bin/convert` is installed now.  Might need to refresh something to get them to regenerate though, not sue how the mediawiki instance works.  @Umcaruje @Lukas-W any idea?

**Comment by Spekular** [comment]
fixed! thanks :)
