### ISSUE TITLE
Forum down?

### ISSUE THREAD

**Issue by DeRobyJ** [LMMS/lmms.io#184]
In case no-one noticed, but I think you had, the forum seems down.

![screenshot_127](https://cloud.githubusercontent.com/assets/6437521/15668267/aa05af4a-271a-11e6-9398-627bd4e92501.png)

Hope it's nothing serious xD

**Comment by musikBear** [comment]
yep here (Denmark) too :+1:

**Comment by Umcaruje** [comment]
I'll look into it.

**Comment by Umcaruje** [comment]
@tresf out inodes piled up again...

Gonna manually fix it usin the solution from #173

**Comment by Umcaruje** [comment]
Fixed.

**Comment by softrabbit** [comment]
It worked manually but not from the script that cron runs?

**Comment by tresf** [comment]
> It worked manually but not from the script that cron runs?

Correct.  Support wrote the cron scripts (from what I read on PHP, this cleanup is supposed to be automatic, so I opened a bug).  I reopened the ticket today when this happened.  They say they can confirm the cron job is not working properly and they are looking into it (lol).

**Comment by musikBear** [comment]
The layout is different now. Can we get 'our old' layout back? Its nice to be able to see posting details, and the old layout was simply more readable

**Comment by Umcaruje** [comment]
@musikBear what?

**Comment by musikBear** [comment]
@Umcaruje  It is a different layout now, or 'skin' if you understand that better. One of the things i have not found in this layout, is the ban-hammer-option. 
I believe it was tresf that installed the previous layout? Not sure.

Indecently, the first time i went in after the issue was solved by you, i got several popups offerings for expansion-packs for moderation only. All costed money. Some were expensive. I said no to all.  Dont know why i got those, and its not important, just thought you should know.

**Comment by tresf** [comment]
> i got several popups offerings for expansion-packs for moderation only. All costed money. Some were expensive. I said no to all. Dont know why i got those, and its not important, just thought you should know.

Stop this rubbish.  We don't do that and neither do our forums.  This is not related to our site.

> @Umcaruje It is a different layout now, or 'skin' if you understand that better. One of the things i have not found in this layout, is the ban-hammer-option. 

Just change it back to whatever it was before.  It's in your preferences.
![screen shot 2016-06-04 at 2 48 20 am](https://cloud.githubusercontent.com/assets/6345473/15798206/f162d6d8-29fe-11e6-8fe3-6b1acae532ce.png)

**Comment by musikBear** [comment]
> Stop this rubbish. We don't do that and neither do our forums. This is not related to our site.

It was the phpBB that offered those addons. 
> Just change it back to whatever it was before. It's in your preferences.

That i did not know. T.y.

**Comment by Umcaruje** [comment]
This is not PhpBB, its the author of our theme. He put a lot of work on his theme, and its perfectly ok that he offers these compatibility packs to get some funds to support him. As a matter of fact, we use the sortables captcha, and he gave me the extension without asking for money, and is always there to help out and change stuff. You can simply hide the message by pressing the big Hide message button. I think the theme integrates much better into our website, and I won't be changing it back to the default PhpBB theme, so please don't ask for that.

**Comment by musikBear** [comment]
> This is not PhpBB, its the author of our theme

@Umcaruje That explanation cleared everything. Both the strange messages, and the fact that i did not recognise the theme, which was no problem in it self, but The only thing i still am a little sad about, is that after the update, the very useful **ban-hammer** option is no longer available. I liked that ban-hammer -option, when i cleaned up after a spammer.

**Comment by tresf** [comment]
@musikBear 

1. Login
2. Go here: http://lmms.io/forum/ucp.php?i=373
3. By "Board style" change it to pro silver

Furthermore, if you want a paid plugin, we'll buy it, just let us know which one and how much.

Your comments are off topic, so if you want to discuss this further, please start a new topic.  This one is closed.
