### ISSUE TITLE
Make database setup more straight-forward

### ISSUE THREAD

**Issue by teeberg** [LMMS/lmms.io#189]
To reproduce #149 locally, I'm trying to set up the LSP on my machine. According to https://github.com/LMMS/lmms.io/wiki/LSP-Installation, I need to "obtain a tarball of the SQL database". How would I go about doing that? Could you maybe upload a snapshot of the current LSP somewhere and link to it from the Install instructions, as to make it as easy as possible for me and other contributors to get started? Even an empty database dump to have the schema would be helpful to have/document somewhere! I can populate the database myself too! :)

**Comment by tresf** [comment]
@teeberg I can email you a copy, just email me tres.finocchiaro@gmail.com.

Once you have a good process for getting others involved (e.g. scraping and uploading the schema) please feel free to tackle that if you feel so inclined.  Also, we don't get much help over here on the site side, so if you're ok with being an admin, we could certainly use the help. 👍

**Comment by teeberg** [comment]
I'm not familiar with the typical ways of managing databases in PHP, but a quick google brought me to http://propelorm.org/ which looks really promising. Once I have the database, I'll see how easy that is to set up.

**Comment by tresf** [comment]
@teeberg this has gone stale.  I think you can just grab the `CREATE ...` statements from the database dump and provide those in the wiki.  I'll leave open because to keep LSP alive, we need this type of information in the wiki.

**Comment by liushuyu** [comment]
Fixed in f8ea1125fafb79aa71178a29d896698ff800be3f

Migration scripts are now available
