### ISSUE TITLE
AOSC OS is shipping LMMS

### ISSUE THREAD

**Issue by MingcongBai** [LMMS/lmms.io#193]
Hereby proposing adding AOSC OS to the download page, as to my reasoning, there are two:

- AOSC OS provides both a RPM-based and a DPKG-based (mainline) distribution, therefore instructions should include both with using `apt` and `zypper` at the same time.
- AOSC OS's `lmms` package comes with complete functionality (including VST, which should work out of the box with all necessary dependencies installed).

However, all of the distribution instruction provided in the page really wouldn't work on AOSC OS (or at least inappropriate in practice). Is there any chance AOSC OS can make it onto the page?

------------------

P.S. Some initial investigation shows that lmms.io uses @Lukas-W's `font-linux`, so I have made an addition to add AOSC OS's logo...

https://github.com/Lukas-W/font-linux/pull/19

**Comment by tresf** [comment]
Sure.  You can add it here: https://github.com/LMMS/lmms.io/blob/master/templates/download/linux.twig

Alternately if you don't have the time, we can add it once the font get approved.  I'm not sure how @Lukas-W does the versioning as we link against `font-linux 0.1` whereas the latest release is `font-linux 0.5` so that may need to be updated as well. 👍

**Comment by MingcongBai** [comment]
> Alternately if you don't have the time, we can add it once the font get approved.

I think I should wait for that first so nothing else gets messy on the way.

**Comment by Lukas-W** [comment]
`fl-aosc`is now included in `font-linux 0.6`.

**Comment by MingcongBai** [comment]
Thank you! Should I move on to create a PR or...?
2016年7月8日 09:32，"Lukas W" <notifications@github.com>写道：

**Comment by tresf** [comment]
> Thank you! Should I move on to create a PR or...?

Yes, please do.  You can add it here: https://github.com/LMMS/lmms.io/blob/master/templates/download/linux.twig

**Comment by MingcongBai** [comment]
PR created: https://github.com/LMMS/lmms.io/pull/194.

Thanks for the inclusion!

**Comment by Umcaruje** [comment]
Closed via #194
