### ISSUE TITLE
forum has a reminder popup

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms.io#195]
This popup appears every time a topic is opened on forum
![forumpop](https://cloud.githubusercontent.com/assets/6662066/16949144/54b851da-4db9-11e6-8c25-d59eddfcc749.JPG)
No matter which of the 3 options are chosen, the popup is shown over and over.
The dl link btw lead to a 404 page on github
https://github.com/ComBoot/ComBoot-3.1/archive/v1.1-rc3.zip

Noone on forum has made a hazzle about it, so i guess i am sole beneficiary .

**Comment by tresf** [comment]
Yes, this is unbearable.  @Umcaruje any advise here?  The buttons don't seem to dismiss it.

@musikBear this may be a moderator/admin only message, but regardless, it's terribly annoying.  As a workaround, you can reset the theme to prosilver and it will go away for your own login session.

**Comment by Umcaruje** [comment]
I'll see to update the theme tonight, and permanently disable all notifications

**Comment by musikBear** [comment]
@tresf Thanks for the tip! :+1: 
I have realized that there is a second message in top of the screen, if the mouse is placed there, but it disapears really fast
It read: 
*Thank you for installing the update! If you updated, but this message does still appear, please change the meta value of theme-version in the overall-header.html file!*
Im not sure if that is a local, or server file. In fact i dont understand the message :´p

**Comment by Umcaruje** [comment]
Updated, if this resurfaces, please reopen

**Comment by Umcaruje** [comment]
Also disabled further notifications in the config, so we shouldn't be getting these notifications anymore.
