### ISSUE TITLE
SoundCloud to remove Groups

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms.io#196]
In a month, SoundCloud will be removing the groups feature .  AFAIK, this means people will not be able to share music to the LMMS group and we won't be able to feed it to our community page.

I'm not sure if there's any sane replacement for this, so we'll likely have to abolish the soundcloud account altogether unless we can switch to something like using tags/hash tags.

> Hey LMMS Service,
> 
> We’re constantly looking for ways to make it easier for creators to share their work and connect with new fans. As well as adding new features and updates, we review existing features to see if they’re still beneficial to the community.
> 
> As we dug into the best ways for curators to connect with artists and fans, we found that Groups aren't working as well as reposts, and curated playlists.
> With that in mind, we’ve decided to phase out Groups on Monday, August 22nd to make room for future updates.
> 
> Until then, you can collect, like or repost the content you would like to save, and connect with your fellow Group members.
> 
> As a Group moderator, we understand the following you’ve built by moderating submissions to your Groups -- we suggest to keep that following going by creating a profile to curate. You can use Reposts and Playlists to share suitable tracks, and accept submissions via Messages.
> 
> We’d love to hear your thoughts on how we can continue to improve your experience on SoundCloud. Send your ideas and feedback by replying directly to this email.

**Comment by socceroos** [comment]
Yeah, the reposts and playlists seems a suitable, if not slightly annoying replacement. People will just have to send a message to the LMMS user requesting a re-share/playlist add of their track.

**Comment by Umcaruje** [comment]
>Yeah, the reposts and playlists seems a suitable, if not slightly annoying replacement. People will just have to send a message to the LMMS user requesting a re-share/playlist add of their track.


Imagine the amount of requests we will get... Still mad at soundcloud for doing this. We'll need to find a different platform to do BoL now, probably a google form.

**Comment by Spekular** [comment]
What about using a tag? Would that solve the issue of the lmms.io feed, or
is it not possible to have a tag feed?

**Comment by tresf** [comment]
I think a tag is mandatory.  Can someone find out how API against it?

**Comment by rogersachan** [comment]
@tresf The link is now broken, the site just sends me to an advertisement for Soundcloud GO.

Unless LMMS was bought by Soundcloud, we should remove it until we have an alternative.

**Comment by tresf** [comment]
> @tresf The link is now broken, the site just sends me to an advertisement for Soundcloud GO.

Because you're on mobile.  Just click the "Continue to soundcloud" link underneath the ad.

**Comment by rogersachan** [comment]
@tresf Then it just sends me to the soundcloud front page.

It also now looks like Soundcloud Groups have been fully removed, any alternative?

**Comment by tresf** [comment]
> @tresf Then it just sends me to the soundcloud front page.

Because their website/app integration is terrible on mobile.  No surprise.  Mine loads fine BTW.

> It also now looks like Soundcloud Groups have been fully removed, any alternative?

Not unless we go [3rd party](https://soundcloudgroups.com/), no.

**Comment by Umcaruje** [comment]
Well we solved this this year by using google forms and offering a public spreadsheet with the entries. There's an idea to post a soundcloud playlist of the winning entries, and if the artist can't host the song on their soundcloud, we can use the service account for that song.

So, should we close out this issue as fixed?

**Comment by tresf** [comment]
I felt the spreadsheet and form from a mobile-friendly and playback-friendly perspective could have been done better by something like we've built into LSP and I'm certain we could code a submission form in 3 days that blows the previous methods out if the water.

That said, there's only so much time in a day and you're right it worked. \*shrug\*

**Comment by tresf** [comment]
Spreadsheet has been live for two years.  Closing.
