### ISSUE TITLE
WOT Blacklisted web links of Facebook page

### ISSUE THREAD

**Issue by SirBothersome** [LMMS/lmms.io#197]
I'm not sure if this is the right place to post this, but I decided to check LMMS's Facebook page today and saw this
![blacklist](https://cloud.githubusercontent.com/assets/20342439/17946764/b8dee99c-6a17-11e6-8737-4be3f331de5d.PNG)

I checked out the link shortener on Web of Trust's website to find less than sparkling reviews. https://www.mywot.com/en/scorecard/bit.do?utm_source=addon&utm_content=popup
I don't think everyone has WOT but for me this was a really big turnoff.

**Comment by tresf** [comment]
Yeah I tend to agree.  URL shorteners aren't needed for this particular post.  We'll correct it and use full URLs moving forward, thanks.

**Comment by tresf** [comment]
Fixed.  Note, the soundcloud groups have been removed, so that link was dead anyway.

![image](https://cloud.githubusercontent.com/assets/6345473/17954068/62fd3162-6a46-11e6-9049-13985dd1b210.png)

**Comment by tresf** [comment]
@SirBothersome did you read the reasons for this reputation score?  They're all abuse reasons (which users create, not the shortener services).  It's not fair to punish `bit.do` for these.  Please provide some solid evidence that `bit.do` is shady in the form of evidence so you aren't wasting our time with false-positives.

**Comment by SirBothersome** [comment]
@tresf , the point is not that the website is/is not shady, the point is that the links it made were blacklisted. If I had tried to click on them, my browser plugin would have prevented me from going to the links. While not every plugin would have done this, it appears that the major players would. [http://www.urlvoid.com/scan/bit.do/](url) Also, the link provided is http, not https,
![http vs https](https://cloud.githubusercontent.com/assets/20342439/17974361/c8ef97c2-6ab3-11e6-8867-c6b820693ca9.PNG)

**Comment by tresf** [comment]
> @tresf , the point is not that the website is/is not shady, the point is that the links it made were blacklisted. If I had tried to click on them, my browser plugin would have prevented me from going to the links. 

If you have a service with blindly blocks URL redirectors that is a problem you've created for yourself.   All URL shorteners will be abused and will be reported with a bad reputation for services that take the consensus of the uneducated versus investigating.

In regards to HTTPS, `bit.do` supports it just fine and uses a trusted SSL certificate to do so, it just doesn't append it to the links by default.

**Comment by SirBothersome** [comment]
![blacklist](https://cloud.githubusercontent.com/assets/20342439/17977253/f256b428-6abe-11e6-9ce2-cdd6830ae787.PNG)
What I was actually referring to when I said "links provided". My English bad. However, as this is closed now, I don't see much purpose in continuing this discussion.
