### ISSUE TITLE
Forum spam

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms.io#2]
This plugin makes the registration hashes less predictable by spammers:

https://www.phpbb.com/customise/db/mod/daropl_antispam/

It does not list our current version 3.0.12 as supported and may break upgrades so I'll leave this bug.

This was recommeded by @eagles051387.

![image](https://cloud.githubusercontent.com/assets/6345473/3800546/ba729682-1bf9-11e4-8d23-92bad48aaed0.png)

**Comment by Umcaruje** [comment]
Is this still a problem? I haven't seen much spam on the forums lately. (But to be honest, I don't visit them much).

**Comment by Sti2nd** [comment]
Yeah, I think musilBear is deleting spam each week :) I have deleted just a few posts

**Comment by Umcaruje** [comment]
I just installed [Cleantalk](http://cleantalk.org/phpbb31-anti-spam-extension) trial on our forums and reenabled account creation. If it proves good in preventing spam, I think we could invest in a plugin like this (8$/year).

**Comment by tresf** [comment]
Thanks.  I assume the privacy policy doesn't allow them to collect our data?

**Comment by Umcaruje** [comment]
https://cleantalk.org/publicoffer#privacy 

As far as I see from here, they won't sell or redistribute our information to anyone.

**Comment by tresf** [comment]
This clause seems slightly sketchy...

> Cookies can be used to implement activities to promote the Service, by using AdWords features: remarketing, interest categories, similar audience. Other types of interest-based advertising, demographic and geographic targeting.

**Comment by Umcaruje** [comment]
Hmm yeah... 

There aren't many advanced anti-spam addons for phpbb 3.1 though

**Comment by Umcaruje** [comment]
Well the service sucks. I removed the extension. I added a new sort of captcha though, that should be helpful.

**Comment by Umcaruje** [comment]
Since this extension is outdated, and I implemented a new captcha which blocked almost all the spam (haven't seen forum spam in weeks) I will close this issue. Please reopen if you disagree with me.
