### ISSUE TITLE
Ad a VST 'red-list' to wiki

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms.io#202]
As you all know we have a list over VSts that has been tested and works in lmms.
However it is not kept updated, and the real reason for that is, that _most_ vsts will work in lmms. So the current list will not give the best info about using vsts.
How about making a list of those vsts that do _not_ work?
A red-list of those that has failed. It will be a short list, and it will have real valuable information, and as the project evolve we can remove red-listed vsts. 
I do not say this list ´should replace the current list, not at all! It should just be a complementary tool, for those that are about to dl and install a vst. They could then glance the red-list, and see if it is worth it at all. 
I felt i better present the idea, before i made the list, in case you all hated the idea.

**Comment by tresf** [comment]
> Maybe you mean "Black-list"

Sure, but they aren't black-listed, they're just broken. 😄

**Comment by musikBear** [comment]
:) red or black as long as its not racial motivated..
(in a way that is interesting. Here in Denmark we would say *red-listed* for those that are faulty, a blacklist, would be those that are prohibited for some reason. For instance illegal software like pirate-bay, they are black-listet   ('sortlistet') on danish internet ..Yes 'we' are like china, 'We' censure the internet..)
Nwm. Il make a list over those ~15 or so, that i know fails in current lmms

**Comment by JtLively** [comment]
@musikBear are you putting that info in the Github wiki ?

**Comment by tresf** [comment]
@JtLively I believe he's talking about our mediawiki instance i.e. http://lmms.io/wiki/index.php?title=Tested_VSTs.

**Comment by JtLively** [comment]
Thanks @tresf. I think that bottom list should include dates tested. Might be easier in a table with Linux and Windows columns. Why is this issue still open ?

**Comment by tresf** [comment]
> Why is this issue still open ?

Perhaps because @musikBear creates bug reports faster than the team can close them. <3

**Comment by musikBear** [comment]
Only those i find :p -But i also posts ideas, but only those i have..
Dates- @JtLively yes that could be, but i plan to go through the no-go's with each lmms-release so those on the list they are currently un-useable, so the date is kind of 'now'

**Comment by Umcaruje** [comment]
This is as easy as just adding the VST's that don't work to the wiki table. Having another list would be reduntant. Closing.
