### ISSUE TITLE
free advanced open source libraries

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms.io#203]
http://superpowered.com/
I dont know if any of these could be of interest, but there are f.i. a library for pitch and stretch opp.
http://superpowered.com/free-open-source-time-stretching-pitch-shifting

Just wanted to show uall

**Comment by liushuyu** [comment]
It seems like this library is not an open source one. It is a commercial closed-source library, which only provide the source code of the demos

**Comment by musikBear** [comment]
@liushuyu  wrote
> commercial closed-source library, which only provide the source code of the demos

They should be ashamed :-1:  How can they write **free-open-source**-time-stretching-pitch-shifting, if its not. Oh well :/

**Comment by tresf** [comment]
> It seems like this library is not an open source one. It is a commercial closed-source library, which only provide the source code of the demos

Despite the commercial options available, [Rubber Band is GPL](http://breakfastquay.com/rubberband/license.html) as is [SoundTouch](http://www.surina.net/soundtouch/license.html).

I'm not sure `@lmms/lmms.io` is a good place for this information, but it's good information nonetheless.

**Comment by tresf** [comment]
@musikBear I'm closing this out because there's not much that can be done on our website regarding it, but it's good information to go back on if we decide to use a 3rd party time stretching library.  👍
