### ISSUE TITLE
Forum has no pin-to-top option

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms.io#208]
I would like to pin the forum- *new-user-introduction* thread, but there is no option, that i can see for pinning a topic, is that because i am dim and not see it, or is that simply no option.

**Comment by Umcaruje** [comment]
![image](https://cloud.githubusercontent.com/assets/6282045/21422341/8702a43a-c837-11e6-9dae-d3d8228998ea.png)
Change the topic to sticky.

**Comment by musikBear** [comment]
Oh but you see, i do not have those options:
![nosticky](https://cloud.githubusercontent.com/assets/6662066/21423821/56eb9826-c83f-11e6-9f58-b962acf57fd7.JPG)
