### ISSUE TITLE
What can LADSPA-plugin-Browser do for a user?

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms.io#211]
Im in the process of testing 1.2.0 RC, and in menu | tools, lmms has the **LADSPA-plugin-Browser** 

Why is this a feature in lmms?
I can open the list, and find a plugin -fine, but i cant load that plugin.
Double-click (first available item) results in an inspection form.

![ladspapluginbrowser](https://cloud.githubusercontent.com/assets/6662066/21858565/df9408b2-d829-11e6-9369-5e1ab330f61a.PNG)

Again, nothing to do. Cant change values, or drag anything anywhere in lmms.
Is LADSPA-plugin-Browser just a nerdy leftover, or does it actually have a functional ability in lmms

tyia.

**Comment by tresf** [comment]
> Why is this a feature in lmms?

It appears to be a tool to help developers understand the plugins (how they receive their input and if they are compatible with LMMS).  It's not really that useful to someone making music.

If you have a proposal for it, please reopen this bug report with a better description.
