### ISSUE TITLE
Hosting the installers on lmms.io as well as Github

### ISSUE THREAD

**Issue by Umcaruje** [LMMS/lmms.io#217]
This recent Amazon s3 outage has got me thinking, we should probably mirror the installers on our servers or somewhere else as well. 

We just had a user who couldn't download 1.1.3 come to discord cause of the outage. And even before some people had general issues with the speed of the download from github.

Interested in hearing your thoughts.

**Comment by tresf** [comment]
I think a mirror is always a good idea however we are always at the mercy of a provider.

 - GitHub goes down on occasion and that is devastating to development.
 - Sourceforge has had reliability issues for our msys2 environments (common enough to write it into our procedures)

If we do roll our own mirrors, I vote we make it part of the `maintenance_tasks` scripts and have it automated.  Perhaps one advantage to this approach is we can buy a digital certificate for the Mac and Windows installers and place them there as well.

**Comment by tresf** [comment]
We can use scp for file transfer if this is ever resurrected.  It does suck to have a single-point-of-failure, but to be fair... even when GitHub [was hit with a DDOS attack, it was back up in 5 minutes]( https://githubengineering.com/ddos-incident-report/).  Closing as stale.
