### ISSUE TITLE
adding a zip on hub and here, fails

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms.io#218]
Hub does not accept zip-files as attachment, neither does this place.
Error thrown
>We don’t support that file type. with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP. 

Even though its stated that ZIP is valid, it wont accept any.
I tried with both a mmpz in a zip-file, and mmp, zipped. Both fails.

**Comment by tresf** [comment]
How is this our problem?

And what is "hub" vs "this place"?

**Comment by Umcaruje** [comment]
This is not our bug. If you need help with this please hop over to Discord, so we avoid making these kind of issues.
