### ISSUE TITLE
users with opensuse & leap has issues

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms.io#222]
This is the thread
http://lmms.io/forum/viewtopic.php?f=7&t=8477&p=29185#p29185
The linux stuff is beyond me, and even beyond the seasoned linux-user Gps
I have asked for the packman name in the initial contact. @tresf

**Comment by tresf** [comment]
Creating bug report on behalf of submitters just causes a mess.  Please encourage the user to interact with us directly either through discord, our mailing list or through this tracker.  Closing.
