### ISSUE TITLE
Link to gentoo package is missing

### ISSUE THREAD

**Issue by jonasstein** [LMMS/lmms.io#235]
Please add a link from
https://lmms.io/download/#linux
to
https://packages.gentoo.org/packages/media-sound/lmms
Thank you

**Comment by tresf** [comment]
We're moving away from repo provided packages and focusing our attention on `AppImages` instead per https://lmms.io/download (scroll to beta).

This is easier for us to support and provides an easier to maintain downloads page.

If someone wants a disto added to the new `other options` section, we'd be happy to accept it in the form of a PR.  I'm closing this out as wont-fix as this area of our site is deprecated with the addition of a Linux x86-64 package.
