### ISSUE TITLE
Purge lmms/hydrogen-drumkits repo

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms.io#239]
At one point in time, @tobydox wrote a way to incorporate Hydrogen drumkits directly into LMMS.  This is in a repo appropriately called `lmms/hydrogen-drumkits`.

The repo has some CMake logic which bundles installers into a self-extracting executable that when run can extract filed [directly into the LMMS samples directory](https://github.com/LMMS/hydrogen-drumkits/blob/master/CMakeLists.txt#L89).

This repo has been mostly unmaintained and to the best of my knowledge unrequested as long as I've been involved, I vote to archive it or purge it.

If we want to keep this alive, this may make more sense as a cmake option to our existing installer (one which copies, converts and installs the appropriate files) but to comply with the [new sample rules](https://github.com/LMMS/samples/blob/master/README.md#legal-rules), I'd like to just get rid it of anyway, since the licensing is [mixed](https://github.com/LMMS/hydrogen-drumkits/blob/3866e4d4fdc5190c97a181975054eb4710ecf4a7/K-27_Trash_Kit/license.html#L310) and certainly not `CC0`.

@SirBothersome @Hussam-Eddin-Alhomsi @iamwontolla (and others I've forgotten).

**Comment by SirBothersome** [comment]
@tresf agreed. I seem to remember some of the kits being licensed GPL (which is odd, I'll try to find some screenshots later), and the origins of the kits are murky. I don't think anyone will miss the samples (although we are in need of some acoustic ones), and in-house sample production is appearing to be viable, so we can cover what the purge will take for the most part. On a side note, why is this in the .io repo?

**Comment by tresf** [comment]
@SirBothersome agreed, GPL is a terrible license for artwork in general, so I think that's reason alone to not use the repo, but what Toby's done to package it up and install it as a side-loaded plugin is cool too.  Perhaps the greatest value in this repository is it's a good first example of what a sample pack could look like.

I think moving forward the sample packs should be a plugin-able format.  Something that allows LMMS to open, extract and place accordingly.  The advantage to Toby's installer idea is that it allows the samples to be written to the LMMS install directory.  I'm not sure if this is good or bad as most people put custom samples in the LMMS working directory instead.  Thanks for the feedback.

**Comment by mikobuntu** [comment]
I agree with archiving it, mainly for backward compatibility.

**Comment by SirBothersome** [comment]
A vote for archive, but solely for analysis.

**Comment by tresf** [comment]
> archiving it [...]  for backward compatibility.

Can you please elaborate on what you mean "backward compatibility"?

**Comment by tresf** [comment]
No objections.  Done.  Archived here: https://github.com/tresf/hydrogen-drumkits/
Windows desktop installer reproduced and provided for archive purposes here: https://github.com/tresf/hydrogen-drumkits/releases

I've emailed GitHub to make my own fork the upstream fork in the event we get push-back (e.g. downstream packaging, etc).
