### ISSUE TITLE
Purge lmms/lsp2

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms.io#240]
@tobydox started working on `lmms/lsp2` in 2014 as to replace the [existing LSP](https://lmms.io/lsp), but in a more modern framework (python/django).

Since then, @Lukas-W has committed some changes, notably a script to import the LSP1 files and some various code fixes and cleanup, but all still in 2014.

The repository has been stale for about 3 years and I wonder if this should stay or if it should go?  We are in dire need of a new LSP however I'm not sure how much time the project has to dedicate to this in the foreseeable future.

**Comment by liushuyu** [comment]
>in a more modern framework (python/django).

Python + Django is still popular, IIRC Instagram is using this combination.

Since this is a decision made back in 2014, I am curious to know why @tobydox wanted to make a switch.

**Comment by tobydox** [comment]
Because using a dedicated web framework with an integrated ORM is always the better choice compared to reinventing the wheel and produce lots of dirty insecure PHP code with manual DB queries etc... I didn't know better almost 10 years ago but nowadays there are so many good solutions and frameworks (not to mention Python (3) as IMHO a far better alternative to PHP).

**Comment by tresf** [comment]
I was hoping to get a clear answer from @tobydox or @Lukas-W.  This repo can certainly live inside a personal repository until it eventually comes to life.  Any thoughts about cleaning up the house here? :)

**Comment by Lukas-W** [comment]
We can transfer ownership to my account for the time being if you want.

**Comment by Lukas-W** [comment]
It would however make it invisible to visitors and potential developers, making it even more unlikely that it will come to life.

**Comment by tresf** [comment]
> We can transfer ownership to my account for the time being if you want. 

That would be my vote.

>  It would however make it invisible to visitors and potential developers, making it even more unlikely that it will come to life.

I don't think it will influence the chances of resurrection.  I have a feeling if it's resurrected, one of 5 people on earth will do it, and they'll know where to look.

I'll leave the choice up to you @Lukas-W as I think you're the most likely to start coding this again.  Of course, one other option is to submodule it over to `lmms.io` and actually stand-up a test site. :)

**Comment by tresf** [comment]
@lukas-w let's pull the trigger on this.  Option is here: https://github.com/LMMS/lsp2/settings, click Transfer and type your name.  I can only do it to my own account, so I'll need you to do it, then we can close this issue.

**Comment by lukas-w** [comment]
@tresf Done.
