### ISSUE TITLE
Refactor lmms/samples

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms.io#242]
The repo `lmms/samples` is finally getting some contributors and the new samples will all be licensed `CC0`. This is great.

After talking with some of the developers on discord, we decided this could also be a home for presets and perhaps even project files and brought into `lmms/lmms` as a `git submodule` or a `git subtree`.

The proposal is to rename the repo `lmms/assets`.

If there are no objections, we'll be doing this shortly.  Anyone that has forked the `lmms/samples` repository may run into problems, so we would like to coordinate this with the team doing the work on this repo (make sure all forked progress is merged).

@SirBothersome @Hussam-Eddin-Alhomsi @iamwontolla (and others I've forgotten).

A somewhat side-topic is the `lmms/artwork` repository.  This just contains a bunch of SVG and Gimp source files and a few renderings.

I think our future theme may obsolete most of these by leveraging SVGs when possible directly in the codebase.  Assuming people want to keep the `lmms/artwork` repo around, this may be a good candidate to place inside the `lmms/assets` repo (and we'd ignore it when doing our `git subtree`).  Opinions welcome.

**Comment by SirBothersome** [comment]
@tresf this seems reasonable. Assets is a good cover-all name and we have been lacking presets for Monstro, Watsyn, etc. I think with the widened scope and change there are two things we need to factor in. 1) @Hussam-Eddin-Alhomsi @iam wontolla and I were given push access to the sample repo by @Umcaruje . In the event of a restructure we'll probably need to be regifted with access. 
2) with new presets and project files potentially coming in we will need someone running quality control. @Hussam-Eddin-Alhomsi has more or less assumed this role for the samples, but I think assigning him quality control for ALL assets would be an unnecessary burden. In addition to Hussam I think @stakeoutpunch  @unfa or @jousboxx would all be excellent candidates for quality control. But I definitely think we should encourage sample and preset contribution before project files

**Comment by tresf** [comment]
>  In the event of a restructure we'll probably need to be regifted with access.

We'd just rename the repo, permissions will be the same.

> with new presets and project files potentially coming in, we will need someone running quality control. 

They won't come in right away necessarily, they'll just be the home. 

> I think @StakeoutPunch @unfa or @Jousboxx would all be excellent candidates for quality control

I agree although we would also benefit from making a nightly job that creates previews of the presets with various notes.  (e.g. something in public domain like twinkle twinkle or something).  We should be able to write an `.mmp` XML project file and do CLI rendering.  Finding a way to host and share the rendering will be tricky but it could offer the QA to spend more time approving and less time opening, closing, dragging and dropping.

**Comment by SirBothersome** [comment]
> We'd just rename the repo, permissions will be the same.

good to know

> They won't come in right away necessarily, they'll just be the home.

I might make some myself

> I agree although we would also benefit from making a nightly job that creates previews of the presets with various notes. (e.g. something in public domain like twinkle twinkle or something). We should be able to write an .mmp XML project file and do CLI rendering. Finding a way to host and share the rendering will be tricky but it could offer the QA to spend more time approving and less time opening, closing, dragging and dropping.

way over my head, but I'll take your word for it

**Comment by Jousboxx** [comment]
I would be happy to do quality control. I can probably also contribute a few samples and presets.

**Comment by tresf** [comment]
@SirBothersome @Hussam-Eddin-Alhomsi @iamwontolla it has been renamed.  For some time, GitHub will automatically redirect `lmms/samples` to `lmms/assets`.  At some point soon, I recommend you backup any work and re-clone the repository under the new name.  Sorry for any inconvenience this may cause and thanks for the flexibility.

**Comment by SirBothersome** [comment]
> I recommend you backup any work and re-clone the repository

@tresf alright, will do

On Thu, Jul 20, 2017 at 11:33 PM, Tres Finocchiaro <notifications@github.com
