### ISSUE TITLE
Midi hardware experts needed for forum

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms.io#243]
This one viewtopic.php?f=7&t=25977
and this one
http://lmms.io/forum/viewtopic.php?f=7&t=25995&p=47532#p47532
are similar in context.
Both owns hardware-synth, but cant connect to lmms
Any input?

**Comment by tresf** [comment]
Please send them to discord. https://discordapp.com/invite/3sc5su7

**Comment by musikBear** [comment]
Thats all very well, but it would be useful to have in writing, not lost in discord-cyperspace, besides at least one is not familiar with english, but i will go discording..

**Comment by tresf** [comment]
> it would be useful to have in writing, not lost in discord-cyperspace

Here then: https://github.com/LMMS/lmms/issues/3724
