### ISSUE TITLE
The website is not being translated

### ISSUE THREAD

**Issue by OzancanKaratas** [LMMS/lmms.io#244]
Website sources was translated, but some problems occurred. Many languages' files is being not compiled. Can you upload an another format of website resource onto Transifex? Like JSON.

**Comment by liushuyu** [comment]
The website is not maintained by me, I don't have access to the web server which means I can't upload translated strings to the server.

**Comment by OzancanKaratas** [comment]
Ok, thanks but what can I do?

**Comment by liushuyu** [comment]
>Ok, thanks but what can I do?

So I guess you want to know how the website looks like in your translated language?

**Comment by OzancanKaratas** [comment]
> So I guess you want to know how the website looks like in your translated language?
Yes of course 👎

**Comment by OzancanKaratas** [comment]
> So I guess you want to know how the website looks like in your translated language?

Yes of course.

**Comment by Umcaruje** [comment]
@tresf can you please provide @liushuyu SSh access, or if you're busy please point me in the right direction :)

**Comment by tresf** [comment]
We use public key authentication, which can be added (from what I remember) through standard means.  The server is running Ubuntu.  @liushuyu can email me his public key and I'd be happy to set it up.

**Comment by Umcaruje** [comment]
Fixed.
