### ISSUE TITLE
Change the star rating system to an upvote based system

### ISSUE THREAD

**Issue by Squatro** [LMMS/lmms.io#246]
The site doesn't have many users that are actively rating the projects, which means that it's really easy for someone to manipulate the ratings of the projects. For example a 5 star project is really easily turned into a 2-3 star project with a few 1 star ratings from someone with bad intentions. Normally this wouldn't be a problem, but as previously mentioned the site doesn't have many active raters. The thing is that this isn't just some speculation about what could happen on the site, but instead a reality. This kind of behavior has been plaguing the LSP for almost a year now and from what I've gathered from the users on the site it really seems to demotivate  the community™.

The fix for this situation would be to change the star rating system to a "like" or "upvote" type of system where the amount of likes, or thumbs up or whatever from users is displayed on the project. Obviously there would be no downvotes, because then we would run intro the same problem again with the 'trolls'.

Thank you for your consideration!
-Squatro

**Comment by gdd71** [comment]
A few more ideas to LSP:
1. Only up-votes or likes counter.
2. Split into two sections/pages:
"Experimental/WIP/non finished" -> As it is now without the rules for shaping and anything
"Completed/Final projects" -> With the requirement and rules for layout
Be a final project, a link to listen, a link to external free samples if used..
So easier can be found more quality projects than others and will also eliminate the possibility the bad guys to evaluate highly bad projects.
3. Enter a hold of 30 seconds or more for the next download of the same project -> This will eliminate manipulation of a download counter.
4. Ability to delete comments from project shareperson.
5. Add emotion icons in comments section.
6. Select theme - dark / light -> With new bright monitors pure white background is not comfortable..
7. Personal avatar picture for users + brief personal information names / years / gender..  - optional  ..

**Comment by tresf** [comment]
The current LSP codebase is just a [maintained version of the old site](http://lmms.sourceforge.net/lsp/index2.php) that @tobydox wrote for the sourceforge page.  The LSP is in need of a complete rewrite.  The current LSP is mostly just the old one wrapped in bootstrap for responsiveness with some link preview logic injected to make it slightly more usable.

The above points are mostly just basic usability improvements that come with a new site.  The hold-download-for-30-seconds is not going to happen though. :)

Closing as out-of-scope for the existing LSP.  If anyone ever comes along and tackles, this, then please copy and paste the points to the new repo.
