### ISSUE TITLE
New Site - Footer Links

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms.io#250]
The footer links for the new site should be changed.

![screen shot 2017-10-21 at 10 14 30 am](https://user-images.githubusercontent.com/6345473/31852621-af6ee438-b648-11e7-9202-409741a3943c.png)

* [x] **GitHub** - Good
* [x] **Facebook** - Good
* [ ] **Soundcloud** - Shouldn't link to our service account.  We don't publish content there.  The live site was changed to `https://soundcloud.com/search/sounds?q=%23lmms` to load tagged songs, but even that may be a bad idea as our announcement is the first result, which is irrelevant to anything really.
* [ ] **YouTube** - Until @cubician takes over our channel and starts publishing content, this link doesn't really have any content.  Recommend we hide it for now.
* [ ] **Google+** - Remove.  On the live site, I've replaced this with a link to Discord, which is where most of the chatter is occurring these days.
* [ ] **Forums** - Not sure if these should be on the bar too, but they're a common place for people discuss, even though forums are so "1997" :)

**Comment by cubician** [comment]
I have a lineup of videos for the YouTube account planned, just waiting for the official 1.2 release so I can include the native EQ as part of the series (Having the Native EQ is a big deal to me.)

But you're right, until I have those videos actually produced the link isn't super productive.

**Comment by tresf** [comment]
Ok, we'll keep it, thanks for the quick reply.

**Comment by Spekular** [comment]
Speaking of the YouTube link, I think that logo is old now. The [new one](
https://www.youtube.com/yt/about/brand-resources/#logos-icons-colors) has
text next to the icon.

**Comment by Umcaruje** [comment]
These were intended like "Social Media" links so I still think they should link to our soundcloud, we could perhaps start reposting songs on soundcloud every week or something.

As for the youtube icon, it'll get updated when font awesome updates it. 

I agree on removing Google +

Not sure about forums, doesn't really fit into the whole social media idea.

**Comment by tresf** [comment]
Our SoundCloud was never intended for reposting (it was for managing the now defunct group).  It's a dead account and it shouldn't receive messages or followers IMO.  If we repurpose this, we can turn the link back on.  It's a waste if real estate and it gives a false image.  It needs to be hidden or removed.

**Comment by Umcaruje** [comment]
Fixed via https://github.com/LMMS/lmms.io/pull/192/commits/38a049cc6347fc58646ca2446dcc420310401207
![image](https://user-images.githubusercontent.com/6282045/34675232-433cd57a-f489-11e7-94f3-43507e81e2fc.png)
