### ISSUE TITLE
New accounts can't log into LSP

### ISSUE THREAD

**Issue by Umcaruje** [LMMS/lmms.io#251]
Reported by @RebeccaDeField 

If you create a new account on the LSP, you can't log in, LSP puts out an error: 
![image](https://user-images.githubusercontent.com/6282045/32077122-9a3207b8-baa2-11e7-8bbf-beeae112e6a5.png)

This could probably be some kind of permissions issue from the website upgrade. This does not affect older accounts, I can log in and upload files fine, which is probably why nobody noticed this.

**Comment by tresf** [comment]
Yeah, it appears [`add_user`](https://github.com/LMMS/lmms.io/blob/6f1a38fa66492098a6362dbfbcb097d542d390c4/public/lsp/dbo.php#L281) doesn't do anything to catch errors, it just displays the ["Success" message](https://github.com/LMMS/lmms.io/blob/6f1a38fa66492098a6362dbfbcb097d542d390c4/public/lsp/register.php#L26) regardless.  I can confirm they aren't being added from a database perspective.  I'll see if there's some simple permissions problems happening.

**Comment by tresf** [comment]
Looks like mysql is running in strict mode, which is OK, but that means the insert statements can't assume certain things.  Fixed via f758532, 7ad3ab5.  @RebeccaLaVie you should be all set.  Thanks for reporting.

**Comment by RebeccaLaVie** [comment]
Login works perfectly on my end now, thank you.
