### ISSUE TITLE
Enhancement: Ability to have profile avatars on the LSP.

### ISSUE THREAD

**Issue by EtornaZ** [LMMS/lmms.io#255]
The title says it all. Does this seem like a good idea?

**Comment by tresf** [comment]
@EtornaZ yes, it's a good idea, but the LSP system is very dated code and this would be part of a larger rewrite effort.  We don't even have a way to reset passwords now.  We're not going to clutter the tracker with LSP requests unless they're absolutely needed.  Closing as wont-fix for now.
