### ISSUE TITLE
LSP still not correctly allowing for new registrations.

### ISSUE THREAD

**Issue by jmortiger** [LMMS/lmms.io#257]
The exact same problem as described in #69 happened to me. I correctly typed out all my info & the security code 8 times, and got the invalid security code error. Even though both #69 and the issue marked as its duplicate, #67 , are both recorded as closed, this problem happened and was solved in the exact same way; switching from Chrome to Edge allowed me to register first try. I even registered again (I messed up my username because I rushed) and it went through without a hitch.

**Comment by tresf** [comment]
@jmortiger it's just a home-brew anti-spam countermeasure.  It's very rare that this bug occurs though, so we haven't pulled the logic.  We can pull it out rather easily though if it continues to cause problems.  What's not immediately obvious is why this occurs on some browsers and not others.  We do the site development against Chrome.

https://github.com/LMMS/lmms.io/blob/master/public/lsp/register.php#L34

**Comment by tresf** [comment]
Someone can revert the problematic code, but it seems some browsers are mucking up the session data causing this.  Closing because the bug seems to be sporadic and we don't have steps to reproduce.

**Comment by allejok96** [comment]
Same thing just happened for me. First I thought it might have been some special character in my password. Now I have 3 accounts :) Firefox 61.0.1 on Arch with Gnome. Restarting Firefox was enough to fix it.
