### ISSUE TITLE
Windows 10 SDL high latency

### ISSUE THREAD

**Issue by r01l** [LMMS/lmms.io#260]
Using SDL on windows 10 I get high latency (~65ms on the built-in sound card, a horrendous ~130ms on an external Focusrite Scarlett). With 1.1.3 and the libportaudio.dll substitution trick and ASIO I get no audible latency at all (on either sound card, with ASIO4ALL for the built-in, and Focusrite ASIO driver for the Scarlett).

I tried lmms-1.1.3-win64.exe, lmms-1.2.0-rc5-win64.exe and lmms-1.2.0-rc5.6545-win64.exe (with experimental audio recording).

(Windows 10 Home 1709 64 bits, Intel i7-6500U @ 2.5GHz, 8GB memory)

**Comment by lukas-w** [comment]
@r01l This bug tracker is for the website only (https://lmms.io). Please submit your report here instead: https://github.com/LMMS/lmms/issues/new

**Comment by r01l** [comment]
Oops, my bad. Sorry.
