### ISSUE TITLE
File upload error

### ISSUE THREAD

**Issue by davidhedlund** [LMMS/lmms.io#261]
![screenshot from 2018-04-25 07 16 51](https://user-images.githubusercontent.com/6416073/39227408-b853fdd4-4858-11e8-9e27-cb2615a24388.png)

I got the same error (but with other ID codes in the square brackets) when I tried to upload a file again.

**Comment by davidhedlund** [comment]
https://github.com/LMMS/lmms/issues/4322

**Comment by tresf** [comment]
@davidhedlund is this still a problem?

**Comment by tresf** [comment]
Closing as this has gone stale.

**Comment by flyingzebras** [comment]
@trebmuh https://lmms.io/wiki/index.php?title=Special:Upload still doesn't work. Please reopen the issue.

**Comment by davidhedlund** [comment]
@trebmuh https://lmms.io/wiki/index.php?title=Special:Upload still doesn't work. Please reopen the issue.

**Comment by tresf** [comment]
Tagging @Umcaruje I don't know how we do files in the wiki.  @flyingzebras we're moving to GitBook and need some volunteers if you're interested.

P.S.  I'm not sure who `@trebmuh` is, you should probably fix that tag.

**Comment by trebmuh** [comment]
> P.S. I'm not sure who @trebmuh is, you should probably fix that tag.

That's me (French translator GUI & website, SF3 support feature demander, plus a few other stuff), but you're right, @davidhedlund looks to have made a mistake when tagging me instead of you.

**Comment by davidhedlund** [comment]
@trebmuh Oh, sorry.

**Comment by trebmuh** [comment]
No worries

**Comment by davidhedlund** [comment]
@tresf 
> we're moving to GitBook

I heard something about this several months ago. When do you think that will actually happen?

**Comment by tresf** [comment]
> do you think it will take months or years to migrate the wiki?

I haven't authored any of the wiki we have, so I'm not sure.  @PhysSong has volunteered to help with the new wiki but we don't have too many other volunteers.

**Comment by davidhedlund** [comment]
>  @PhysSong has volunteered to help with the new wiki but we don't have too many other volunteers.

Thank you for the update. I don't have any time to help my self unfortunate.

**Comment by liushuyu** [comment]
I think this issue is irrelevant now?

**Comment by liushuyu** [comment]
MediaWiki has been updated to a very new version.
Closing. Feel free to reopen if necessary.
