### ISSUE TITLE
Bad label in menu Project in French version

### ISSUE THREAD

**Issue by adaz33** [LMMS/lmms.io#262]
LMMS Version 1.2.0-rc5 (win32/x86_64, Qt 5.4.2, GCC 4.9.4 20150716 (prerelease))

Hi all,
just a little mistake to report in French LMMS, menu Project.
Line below Ctrl+Alt+S (save as new version), "Sauvegarder en tant que omdèle par défaut"?

omdèle  may be replaced by modèle.

**Comment by liushuyu** [comment]
Sorry, but you seemed to report the issue to a unrelated repository. I recommend you to report this issue to https://github.com/liushuyu/lmms-translations/issues

**Comment by Umcaruje** [comment]
@liushuyu is right, this is not an issue for this tracker.
