### ISSUE TITLE
Broken video tutorial link

### ISSUE THREAD

**Issue by ahstro** [LMMS/lmms.io#263]
The first link under [the Automation Editor section](https://lmms.io/documentation/Video_tutorials#Automation_Editor) on the Video tutorials page starts with `httsp` instead of `https`, making it unclickable. Was going to fix it myself, but couldn't find it in the code, so assuming it's fetched from somewhere else? This still felt like the most appropriate place to report the issue though.

**Comment by Umcaruje** [comment]
Hi, thanks for reporting. I fixed it. The documentation is edited at http://lmms.io/wiki 

I can hook you up with a account if you want. Cheers.
