### ISSUE TITLE
Get Involved outdated?

### ISSUE THREAD

**Issue by Spekular** [LMMS/lmms.io#264]
The page focuses heavily on the LMMS mailing list

> See our GitHub Wiki and our bug tracker to get started. Furthermore, the LMMS mailing list is a great place to introduce yourself.

> Public registration on our Wiki is disabled due to spam issues. Please post to the mailing list if you're interested in helping out with the documentation!

> Posting to the mailing list is the best way to reach out to our developers:

As far as I'm aware, this is no longer the most active/best channel of communication. Is this correct?

As a side note, the page also states

> We are in desperate need of new developers to join our team. LMMS is written in C++ using the Qt Framework, so if you know a thing or two about these, don't hesitate to get yourself dirty with coding!

However, elsewhere I believe we encourage people to contribute even if they aren't familiar with C++ and Qt beforehand. Should this perhaps be something along the lines of

> We are in desperate need of new developers to join our team. LMMS is written in C++ using the Qt Framework, but even if you don't have prior experience with these, don't hesitate to get yourself dirty with coding!

?

**Comment by lukas-w** [comment]
> As far as I'm aware, this is no longer the most active/best channel of communication. Is this correct?

This is definitely correct. The mailing list only gets a handful of mails per month max.

However, I'm unsure what method of communication we should promote as the preferred one. Personally, I have very mixed feelings about using Discord a lot for development related discussion. Splitting discussions into several places can make it considerably harder to follow activity on the project, and a lot of valuable conversations are almost impossible to find on Discord after they've happened, rendering the information in them lost. I feel like a good part of the conversations happening on Discord have a better place here on GitHub in the issues they're relating to. 

On the other hand, GitHub's issue tracker arguably is not the best place for introducing yourself or for quickly troubleshooting programming/compilation issues.

> However, elsewhere I believe we encourage people to contribute even if they aren't familiar with C++ and Qt beforehand.

While I'd say we'd appreciate help from anyone, no matter the level of experience, I fear this would be sending out the wrong message. We don't have the people to teach or guide a handful of prospective C++ developers. LMMS has suffered quite a bit from bad architectural design and sloppy coding that doesn't stick to most of the common C++ principles. In my eyes, these are the issues we need fixing the most. However, to do so, we need people who are more - not less - experienced than the current team. With almost fifty open pull requests, we desperately need developers experienced in DSP and C++ who are willing to review code and make decisions on the project. @Wallacoloo has been an invaluable help with reviewing PRs and we need more people like him, i.e. people who know what they are doing.

**Comment by Spekular** [comment]
##### Mailing List

The way I see it, "reach out to our developers" seems more likely to be troubleshooting type issues rather than development conversation. If the conversation ends up being something that would warrant an issue/comment on GitHub, we can direct people to post about it there, or summarize the discussion. This line also falls under the "mailing list" item, so it would be sufficient to remove the implication that it's the best method, rather than redirecting elsewhere.

As for introductions, those aren't exactly something that would need to be documented (unless I'm mistaken), so they could easily be directed to Discord instead. Similarly, I don't think it matters much if someone's request to access MediaWiki gets lost in the chat log. AFAIK whoever hands out MediaWiki accounts should be able to see edit history, right? In a worst case scenario where someone gets an account and starts sabotaging, it should just be a matter of checking which user is making the malicious changes and revoking their account.

##### C++/Qt Prerequisite

I'll defer to your judgement here.

**Comment by tresf** [comment]
@Spekular just fix it please.  Propose and fix if needed (PR, etc).  Tag those needed if you're unsure.  Don't leave bug reports that are opened ended judgement questions... that's what the #lmmsio [Discord](https://lmms.io/chat) channel is for.  Lukas wrote those statements because we needed text from our [old community page](http://lmms.sourceforge.net/community2.php) and if it needs to be improved, just improve it, please. :D

**Comment by Spekular** [comment]
> Don't leave bug reports that are opened ended judgement questions

Resolved!

**Comment by tresf** [comment]
> Don't leave bug reports that are opened ended judgement questions
> > Resolved!

Where?
