### ISSUE TITLE
An invitation to 'sonor' a german conference 

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms.io#267]
http://lmms.io/forum/viewtopic.php?f=4&t=28647#p56932
FYI @tresf @Umcaruje @zonkmachine @PhysSong 
Sonor-conference invite a LMMS spokesperson to preform  a demo, and a presentation talk of one hour!

**Comment by PhysSong** [comment]
This issue tracker is for website development. You should use our discord channel instead.
Anyway, I can't go there because it's too far from here.

**Comment by musikBear** [comment]
@PhysSong I did leave a message on discord. No response, but zonkmashine is on it now, so all's well :)
-Btw -earlier *this* site has been used for different contacting, that was non-related to program-issues, but i know the affection for discord, that exists -for some 👼
