### ISSUE TITLE
"contact us" link on the download page broken

### ISSUE THREAD

**Issue by oldunixguy** [LMMS/lmms.io#272]
Problem 1. 
came here to download. found a problem with the Ubuntu 14 repo version. clicked on the "contact us" link for version support issues. Got 404 not found page.
Problem 2.
Ubuntu 14 repo for lmms when attempting to install with synaptic LOUDLY WARNS this distro could NOT be authenticated.... What should we do? Can this be fixed?
I tried to paste a screenshot but all it does is put the file name in this text.

**Comment by liushuyu** [comment]
>Ubuntu 14 repo for lmms when attempting to install with synaptic LOUDLY WARNS this distro could NOT be authenticated.... What should we do? Can this be fixed?
I tried to paste a screenshot but all it does is put the file name in this text.

Which repository are you using? If you are using the KXStudio, please follow the instructions on https://kx.studio/Repositories#Ubuntu and if you have any further questions, you need to contact them to get your problem resolved.

Thanks

**Comment by oldunixguy** [comment]
here is the repo info for Ubuntu 14 for which the lmms problem happened.

root@PEI:~# dpkg -s lmms
Package: lmms
Status: install ok installed
Priority: optional
Section: sound
Installed-Size: 12315
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Version: 1.0.0+stable-0ubuntu1
Depends: lmms-common (>= 1.0.0+stable-0ubuntu1), libasound2 (>= 1.0.16), libc6 (>= 2.15), libfftw3-single3, libfluidsynth1, libfontconfig1 (>= 2.9.0), libgcc1 (>= 1:4.1.1), libjack-jackd2-0 (>= 1.9.5~dfsg-14) | libjack-0.116, libogg0 (>= 1.0rc3), libportaudio2 (>= 19+svn20101113), libpulse0 (>= 1:0.99.1), libqt4-xml (>= 4:4.5.3), libqtcore4 (>= 4:4.8.0), libqtgui4 (>= 4:4.5.3), libsamplerate0 (>= 0.1.7), libsdl1.2debian (>= 1.2.11), libsndfile1 (>= 1.0.20), libstdc++6 (>= 4.6), libstk0c2a, libvorbis0a (>= 1.1.2), libvorbisenc2 (>= 1.1.2), libvorbisfile3 (>= 1.1.2), libx11-6, libxext6, libxft2 (>> 2.1.1), libxinerama1, zlib1g (>= 1:1.1.4), stk
Recommends: tap-plugins, caps
Suggests: fil-plugins, mcp-plugins, omins, vcf, freepats, fluid-soundfont-gm
Description: Linux Multimedia Studio
 LMMS aims to be a free alternative to popular (but commercial and closed-
 source) programs like FruityLoops, Cubase and Logic giving you the ability of
 producing music with your computer by creating cool loops, synthesizing and
 mixing sounds, arranging samples, having more fun with your MIDI-keyboard
 and much more...
 .
 LMMS combines the features of a tracker-/sequencer-program (pattern-/channel-/
 sample-/song-/effect-management) and those of powerful synthesizers and
 samplers in a modern, user-friendly and easy to use graphical user-interface.
Homepage: http://lmms.sf.net/
Original-Maintainer: Patrick Winnertz <winnie@debian.org>

If this is not what you are looking for please tell me how to obtain it.
thanks
oldunixguy

**Comment by liushuyu** [comment]
>If this is not what you are looking for please tell me how to obtain it.

From the look of it, it seems like you have installed the version from Ubuntu official repository. It shouldn't have the issue that "The package couldn't be authenticated" or "Unable to verify the package".

If LMMS 1.0.0 was what you wanted to install, you have already installed it from the look of it. If you were attempting to install a newer version, then, you need to paste the output of `apt show lmms` and `apt policy lmms`

 >clicked on the "contact us" link for version support issues. Got 404 not found page.

This issue is being addressed: #273

**Comment by oldunixguy** [comment]
Thanks. I was just trying to install any version... this may have installed but it produced the error I reported.
here is more output for you.
thanks
oldunixguy

root@PEI:~# apt show lmms
Package: lmms
Version: 1.0.0+stable-0ubuntu1
Priority: optional
Section: universe/sound
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Patrick Winnertz <winnie@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 12.6 MB
Depends: lmms-common (>= 1.0.0+stable-0ubuntu1), libasound2 (>= 1.0.16), libc6 (>= 2.15), libfftw3-single3, libfluidsynth1, libfontconfig1 (>= 2.9.0), libgcc1 (>= 1:4.1.1), libjack-jackd2-0 (>= 1.9.5~dfsg-14) | libjack-0.116, libogg0 (>= 1.0rc3), libportaudio2 (>= 19+svn20101113), libpulse0 (>= 1:0.99.1), libqt4-xml (>= 4:4.5.3), libqtcore4 (>= 4:4.8.0), libqtgui4 (>= 4:4.5.3), libsamplerate0 (>= 0.1.7), libsdl1.2debian (>= 1.2.11), libsndfile1 (>= 1.0.20), libstdc++6 (>= 4.6), libstk0c2a, libvorbis0a (>= 1.1.2), libvorbisenc2 (>= 1.1.2), libvorbisfile3 (>= 1.1.2), libx11-6, libxext6, libxft2 (>> 2.1.1), libxinerama1, zlib1g (>= 1:1.1.4), stk
Recommends: tap-plugins, caps
Suggests: fil-plugins, mcp-plugins, omins, vcf, freepats, fluid-soundfont-gm
Download-Size: 4,576 kB
Homepage: http://lmms.sf.net/
Task: ubuntustudio-audio
Supported: 3y
APT-Manual-Installed: yes
APT-Sources: http://us.archive.ubuntu.com/ubuntu/ trusty-updates/universe amd64 Packages
Description: Linux Multimedia Studio
 LMMS aims to be a free alternative to popular (but commercial and closed-
 source) programs like FruityLoops, Cubase and Logic giving you the ability of
 producing music with your computer by creating cool loops, synthesizing and
 mixing sounds, arranging samples, having more fun with your MIDI-keyboard
 and much more...
 .
 LMMS combines the features of a tracker-/sequencer-program (pattern-/channel-/
 sample-/song-/effect-management) and those of powerful synthesizers and
 samplers in a modern, user-friendly and easy to use graphical user-interface.

N: There is 1 additional record. Please use the '-a' switch to see it

root@PEI:~# apt policy lmms
E: Invalid operation policy

**Comment by liushuyu** [comment]
@oldunixguy Sorry for letting this issue stale for so long. The issues with the website are now fixed.

If you are still having issues with LMMS itself, please file a new issue at https://github.com/LMMS/lmms/issues/new
Don't forget to include a reference to this issue in your new report so that others can see your issue in the correct context.

Thanks
