### ISSUE TITLE
Languages list

### ISSUE THREAD

**Issue by ImprovingLMMS** [LMMS/lmms.io#274]
To put all the languages of the languages list with the first letter in uppercase.

**Comment by liushuyu** [comment]
>To put all the languages of the languages list with the first letter in uppercase.

The language data in the system provide the names of the languages in the language list. Some of the languages do not capitalize their language names in their languages.

**Comment by lukas-w** [comment]
There's not much else to say here, different languages have different capitalization rules. For reference, this is Google Search's language selection:

![image](https://user-images.githubusercontent.com/2879917/64073374-2c7f9000-cc9d-11e9-8eae-a22e633d38f1.png)
