### ISSUE TITLE
Website translations broken

### ISSUE THREAD

**Issue by trebmuh** [LMMS/lmms.io#278]
It looks that the website translations are broken. Whatever the language I'm selecting, everything is in English. (as an example: https://lmms.io/?lang=fr_FR ).

**Comment by liushuyu** [comment]
>It looks that the website translations are broken. Whatever the language I'm selecting, everything is in English. (as an example: https://lmms.io/?lang=fr_FR ).

This is a design problem in PHP where the website is updated, translation data will become out-of-sync and needs a reload. I have implemented a fix and it should work now.

**Comment by trebmuh** [comment]
Yes it works now.
Thank you @liushuyu
