### ISSUE TITLE
Artwork page has invalid 404 links

### ISSUE THREAD

**Issue by viraxor** [LMMS/lmms.io#283]
This is LMMS icon link:
![image](https://user-images.githubusercontent.com/55741238/69009723-79980780-0958-11ea-8945-978515c86f3d.png)
This is .mmpz icon link:
![image](https://user-images.githubusercontent.com/55741238/69009729-8ae11400-0958-11ea-8dd6-9ac0de1077f8.png)

**Comment by Spekular** [comment]
Worth noting that both of these icons are also out of date. I don't think this will be fixed until/unless the page is updated with the new icons.
