### ISSUE TITLE
Error on wiki for image-upload

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms.io#291]
Attempting to add an image to the wiki on this link
https://lmms.io/wiki/index.php?title=Special:Upload
 throws this error:
![image](https://user-images.githubusercontent.com/6662066/73611609-cb5d3f00-45e3-11ea-93ef-91edca829d45.png)

Process:
![image](https://user-images.githubusercontent.com/6662066/73611726-1e83c180-45e5-11ea-9484-835ce620ef6b.png)

Image is shown as accepted, but actual upload fails

The image that was rejected:
![afp121](https://user-images.githubusercontent.com/6662066/73611681-808ff700-45e4-11ea-90c1-e3503c0b46c1.PNG)

Attempted 3 times 2 days ago + 1 today:
![image](https://user-images.githubusercontent.com/6662066/73611748-5559d780-45e5-11ea-89fb-8bdc3c447529.png)

**Comment by liushuyu** [comment]
It should now resolved.

**Comment by musikBear** [comment]
It is -good work.
