### ISSUE TITLE
Download page says "error 500"

### ISSUE THREAD

**Issue by softrabbit** [LMMS/lmms.io#295]
Getting a 500 on the download page using both Chrome and Edge on Windows 10, both browsers are up to date AFAIK.

**Comment by Umcaruje** [comment]
Looks like #173 again.  `df -ih` gives me
```
Filesystem     Inodes IUsed IFree IUse% Mounted on
udev             228K   423  228K    1% /dev
tmpfs            233K   555  233K    1% /run
/dev/xvda2       1.5M  1.5M     0  100% /
tmpfs            233K     2  233K    1% /dev/shm
tmpfs            233K     4  233K    1% /run/lock
tmpfs            233K    16  233K    1% /sys/fs/cgroup
tmpfs            233K     4  233K    1% /run/user/1001
```

But I can't find the directory where we keep the temp files to clean it. `/home/deploy/lmms.io/tmp` does not exist.

**Comment by Umcaruje** [comment]
Looks like there is a lot of session files in `~/lmms.io/var/cache/lsp`. Cleaned them up, and restarted the fastcgi service but the error still persists. Investigating further...

**Comment by Umcaruje** [comment]
Ok looks like it just took some time. The download page is back.

**Comment by Umcaruje** [comment]
Closing this issue, we should continue at #173
