### ISSUE TITLE
Website FAQ link is broken

### ISSUE THREAD

**Issue by BrandonMakin** [LMMS/lmms.io#301]
The FAQ at `http://www.lmms.io/forum/app.php/help/faq` is a 404.

I got to this URL by going to `http://www.lmms.io/forum/` and clicking "FAQ" in the header.

**Comment by liushuyu** [comment]
Can't reproduce the issue here:
![image](https://user-images.githubusercontent.com/6829345/81140583-19f1e080-8f27-11ea-9bb3-9c9bb988cdfa.png)

**Comment by BrandonMakin** [comment]
On further inspection, I realized I was accessing the forum using HTTP.  The issue appears to only be present with HTTP and not HTTPS.

**Comment by liushuyu** [comment]
>On further inspection, I realized I was accessing the forum using HTTP. The issue appears to only be present with HTTP and not HTTPS.

Thanks for reporting this issue. I have deployed a fix, can you now try and see if you can reproduce the issue again?

**Comment by BrandonMakin** [comment]
I can no longer reproduce the issue.  The FAQ seems to be working properly.  Thank you too!
