### ISSUE TITLE
Sharing Platform not working?

### ISSUE THREAD

**Issue by EzecraftingYT** [LMMS/lmms.io#310]
Today I wanted to get a flute-like sound for my death sound effect from the lmms swapping platform, and I got error 404. I don't know what is wrong, but before this error I tried to open a link to an .xpf file and it was not found.

![LMMS Error](https://user-images.githubusercontent.com/40042886/83337087-efc5e100-a28e-11ea-9b16-55e69a4875f1.png)

**Comment by Spekular** [comment]
Duplicate of #309, LSP is temporarily down for maintenance.

**Comment by EzecraftingYT** [comment]
Oh ok, thanks.
