### ISSUE TITLE
The LSP is making the website go down.

### ISSUE THREAD

**Issue by Umcaruje** [LMMS/lmms.io#313]
LSP changes made the whole website go down. 

The website returns a 504 Gateway Time-out. It appears to have started from this commit https://github.com/LMMS/lmms.io/commit/a37cb4dbbc8c2f97dd8c9b1ccc0b1cf9fcc89497

Internally in the logs it's a lot of `upstream timed out (110: Connection timed out) while connecting to upstream` for the fastCGI processor. When I restart the fastCGI processor I can gain access to the website for brief moments, until someone ultimately tries to access the LSP and then the whole website goes again

As a temporary fix, I renamed `lsp/index.php` to `lsp/noindex.php` directly on the server, also copied the under maintenance page as `lsp/index.html` and did a cosmetic edit 
![image](https://user-images.githubusercontent.com/6282045/83417970-1d439380-a423-11ea-96f8-155670e6708b.png)

@liushuyu please look into this

**Comment by Umcaruje** [comment]
Ok this might also have some other implications other than the LSP, after 10 minutes after restarting the fastCGI processor the gateway timeout error is back...

It's still a lot better with LSP disabled, before the website would be up for maybe half a minute

**Comment by liushuyu** [comment]
So the problem has fixed. For the record, MySQL was hogging all the resources because the current data sets are too large, and the query is too costly. 

The fix was to add an index to the database table like this:

```sql
CREATE INDEX comments_file_id ON comments(file_id);
CREATE INDEX comments_user_id ON comments(user_id);
```

This will make MySQL use the prebaked indexes when doing a query, thus reduce the query cost.
