### ISSUE TITLE
Migrate hosting

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms.io#317]
NetworkRedux -- our hosting sponsor -- will be gone in December according to a recent email.  I asked the Pidgin mailing list and they switched to Digital Ocean.  Some of the below tasks are hosting-specific so I'll assume that's where we're going too unless a better provider comes along.

* [x] Add Digital Ocean logo in place of NetworkRedux https://opensource.nyc3.cdn.digitaloceanspaces.com/attribution/index.html
* [x] Migrate SSH logins (public keys)
* [x] Migrate main website
* [x] Migrate existing GitHub deployment rules (e.g. git-deploy)
* [x] Migrate LSP
* [x] Migrate forums
* [x] Migrate DNS
* [x] Migrate crontabs
* [x] Migrate any hosting-specific rules (e.g. DKIM email authentication, etc)

Some thoughts.... 
* I'm assigning those that are currently responsible for maintaining the current site over at NetworkRedux although it's very likely that just one or two of the assignees will do the bulk of the work.
* I'm chosen Ubuntu for the new server to make the transition easier although Digital Ocean also offers Docker, which I suspect will be popular for the future.
* It's been a while since I've setup a site from scratch, so any work I perform I'll be doing the work locally and documenting as I go.
* We may benefit from a staged-rollout where we alias the old site and start building out the new site piece by piece.  E.g. `lmms.io/forum` -> `old.lmms.io/forum`.  This can break web crawling and stuff so we have to be strategic about it.
* If you think of something, add it to the list please.  We have less than three months to migrate.  The last migration from NetworkRedux back to NetworkRedux (OS upgrade) took weeks to sort everything out, so anticipate that this will take many hours of our time.

--- 

### Obligations to DigitalOcean
... as a sponsored project:

<details>
<summary>Screenshot of requirements from DigitalOcean's website</summary>

![image](https://user-images.githubusercontent.com/6345473/93263443-ca90ac00-f773-11ea-8a66-d3db86cd169b.png)

</details>

* [X] Logo + linkback (see first bullet above)
* [X] Technical overview of DigitalOcean use/setup (one time) [wiki/Architecture](https://github.com/LMMS/lmms.io/wiki/Architecture)
* [X] Announce support with blog post [Forums: "New Hosting" (phpbb)](https://lmms.io/forum/viewtopic.php?f=1&p=72200)
* [X] Twitter shout-out (every 6 months, scheduled @tresf  + @Spekular )

**Comment by tresf** [comment]
@liushuyu I believe the MediaWiki needs some attention.  If it's retired, a single redirect may suffice... Google is reporting this: ```
MediaWiki internal error.

Original exception: [e3cbabc236029127d7263366] 2020-09-15 14:49:31: Fatal exception of type "Wikimedia\Assert\PostconditionException"

Exception caught inside exception handler.

Set $wgShowExceptionDetails = true; at the bottom of LocalSettings.php to show detailed debugging information. 
```

**Comment by liushuyu** [comment]
I think probably this is now finished and could be closed.
