### ISSUE TITLE
Enlace roto

### ISSUE THREAD

**Issue by narsiteo** [LMMS/lmms.io#318]
El enlace href = "http://www.megaupload.com/?d=F9OAT0BQ está roto

**Comment by Spekular** [comment]
Where did you find this link? I'm pretty sure we don't have any megaupload links on lmms.io.

**Comment by narsiteo** [comment]
> Where did you find this link? I'm pretty sure we don't have any megaupload links on lmms.io.

This is the link:
https://lmms.io/lsp/index.php?action=show&file=1078

**Comment by Spekular** [comment]
The LSP hosts user generated content, that link is added to the description by the uploader.

Requesting that this be closed as invalid.
