### ISSUE TITLE
fix translation

### ISSUE THREAD

**Issue by RiedleroD** [LMMS/lmms.io#321]
I've opened the lmms.io website on my phone today, and found that at least the german translation is pretty trash. Also I believe there are also completely missing translations, since there are many empty list points.

![state of the current website translations](https://user-images.githubusercontent.com/57227431/95962044-2c414600-0e06-11eb-8fed-965dae500813.jpg)

Anyway, I can fix all of that if somebody directs me to where I have to put the translations, that'd be very helpful.

**Comment by Spekular** [comment]
https://www.transifex.com/lmms/lmms/

**Comment by RiedleroD** [comment]
should I close this issue or broaden it so people see that there's still translation work to do?

**Comment by Spekular** [comment]
I would say close it.
