### ISSUE TITLE
Can't download LMMS

### ISSUE THREAD

**Issue by toosyz** [LMMS/lmms.io#322]
![image](https://user-images.githubusercontent.com/36548808/96299534-7d169180-0ff4-11eb-9e85-005451db62d3.png)
not a huge problem for me cuz i already have lmms tbh i just wanted to download the newer version cuz its got cooler stuff ill try again tomoz and hopefully succeed

**Comment by DomClark** [comment]
Should be fixed now in c9e71f27fac5cd5215dbe8e963eae3937cda8ed0, thanks for reporting!
