### ISSUE TITLE
SoundCloud "Play" Button

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms.io#33]
Anyone interested in tackling this?  @Umcaruje comes to mind.... :)

The idea is to have an HTML5 play button embedded into the soundcloud feed.  I found a few libraries for this, all seems to leverage HTML5, CSS, JavaScript and sometimes have a flash-player fallback.

The HTML could be appended to the feed body on this line: [soundcloud.php#L20](https://github.com/LMMS/lmms.io/blob/master/feed/soundcloud.php#L20)

The stream is in the JSON data as `stream_url`, or more specifically `$item->stream_url`.  Here's an example `stream_url` for reference:

```html
https://api.soundcloud.com/tracks/164168248/stream?client_id=<BASE64_DECODE_SOUNDCLOUD_CLIENT_ID>
```

To grab this URL with the secret sanely from `soundcloud.php`, you can do:

**PHP**

```php
// echo some html tags, etc
get_secrets('soundcloud', $item->stream_url);
// echo more html tags, etc
```

This will automatically append the decoded API client id to the end of the URL (The disadvantage of course is it exposes the secret to the clients loading that web page)

---

**Mock-Up**

> ![image](https://cloud.githubusercontent.com/assets/6345473/4002164/01b8a6ee-296a-11e4-871d-836b1bd4267a.png)

**Comment by Umcaruje** [comment]
![capture](https://cloud.githubusercontent.com/assets/6282045/5600895/28bafd24-92e6-11e4-92f7-529029cf875c.PNG)
Got it working, needs some minor adjustments, and I'll finish it tomorrow.

**Comment by Umcaruje** [comment]
Implemented per https://github.com/LMMS/lmms.io/commit/785c4924fc77093126451ae930cdddf084f6cc21
