### ISSUE TITLE
Link valido y error 404

### ISSUE THREAD

**Issue by firiox** [LMMS/lmms.io#330]
El link del post esta bien lo copie y funciono pero al utilizarlo clickearlo me lleva a una pagina error 404

**Comment by firiox** [comment]
https://m.soundcloud.com/tropicaldutch/real

**Comment by liushuyu** [comment]
> https://m.soundcloud.com/tropicaldutch/real

Sorry, but which post is this from? Can you provide the link to the post instead?

[Translated] / [Traducido]

Lo siento, pero ¿de qué puesto es esto? ¿Puede proporcionar el enlace a la entrada en su lugar?

**Comment by firiox** [comment]
https://lmms.io/forum/viewtopic.php?f=4&t=4480&sid=f2b45087f3337ba0f11d38ec731371c4&start=110

**Comment by liushuyu** [comment]
> https://lmms.io/forum/viewtopic.php?f=4&t=4480&sid=f2b45087f3337ba0f11d38ec731371c4&start=110

Sorry for the late reply. We are not responsible for any content on the forum, since they are made by the user.

[Translated] / [Traducido]

Disculpe la demora en la respuesta. No nos responsabilizamos de los contenidos del foro, ya que son realizados por el usuario.
