### ISSUE TITLE
IRC channel

### ISSUE THREAD

**Issue by trebmuh** [LMMS/lmms.io#334]
Hey @Spekular and @liushuyu (and others too).

Seeing [this commit](https://github.com/LMMS/lmms.io/commit/4129bafd294fb4393241f4ad7da4320839d325b6), I'm wondering why you did remove the IRC channel link ? It's still a good way to share idea/music and ask question about LMMS.

If that's because of the freenode disaster, we now have a #lmms libera.chat channel and people have already started moving to it.

**Comment by Spekular** [comment]
See [this PR](https://github.com/LMMS/lmms.io/pull/333) for discussion.

No one available at short notice was able to take care of migrating the IRC channel, so rather than continue direct people to one hosted on a shady service we removed it for the time being. I have no idea who's running the channel you speak of, so I personally wouldn't link it from the official site.

**Comment by crabbedhaloablution** [comment]
You can take over the Libera channel by sending an email and verifying your identity:
https://libera.chat/chanreg

**Comment by tresf** [comment]
> You can take over the Libera channel by sending an email and verifying your identity: https://libera.chat/chanreg

We discussed this a bit in #333, but someone please run with this, we'll link it when it's up and running.  We use Discord predominantly, so someone that actually uses IRC is best to spearhead this.

**Comment by trebmuh** [comment]
OK, I'm doing it and will update here when done.

**Comment by liushuyu** [comment]
> OK, I'm doing it and will update here when done.

Thank you! We could help you set up a IRC bridge should you need it.

**Comment by trebmuh** [comment]
OK, I've checked it and it seems that I already am channel operator there (beeing so since may). It seems I forgot I was probably because back then, I was moving to a new job and location.
Anyway, which project maintainer want to be given the operator role too? Note that it needs to be someone with a registrered nickname on the libera.chat server. Please let me know.

@liushuyu : why not, could be good to have, let's discuss that after a maintainer is given the operator role.

**Comment by tresf** [comment]
@trebmuh thank you!  Please add `op` to `tresf`.  Anyone else, please chime in... I'll name a few admins that help out whenever we need to grant access, I expect one or more to chime in (below are their github names, they'll need to chime in once they've registered their libera names).

@Umcaruje 
@PhysSong
@Spekular 
@liushuyu 

For those not familiar with IRC:

1. Visit https://web.libera.chat/ (or use your client of choice)
2. Pick a nickname
2. Join the channel `#lmms`
3. Register a password:
   ```irc
   /msg NickServ REGISTER SomeSecurePassword your.email@address.com
   ````
4.  Use the registration code provided to register
5. Send your nickname here to @trebmuh for `op` access.

**Comment by PhysSong** [comment]
@trebmuh I registered the IRC server as `PhysSong`.

**Comment by liushuyu** [comment]
I have registered as `liushuyu`

**Comment by trebmuh** [comment]
I've added tresf, PhysSong, and liushuyu as op on the channel.
@PhysSong : note that you've been writing clearly your password on the IRC channel, I hope you changed it after!

**Comment by trebmuh** [comment]
I've added @tresf, @PhysSong, and @liushuyu as op on the channel.
@PhysSong : note that you've been writing clearly your password on the IRC channel, I hope you changed it after!
