### ISSUE TITLE
Sharing Platform Search Function Does Not Work on Website

### ISSUE THREAD

**Issue by Bietola** [LMMS/lmms.io#335]
No description is really required... as soon as I hit "search" I don't get search result but only get what seems to be a page referesh.

**Comment by Umcaruje** [comment]
Confirmed. @liushuyu any insights on why this could be happening?

**Comment by liushuyu** [comment]
This should have been fixed in 4aed777020bea35665f20ebeb25f9d451b22467a.

Could you please verify it? Thank you in advance.

**Comment by tresf** [comment]
Seems to be fixed.
