### ISSUE TITLE
www.lmms.io is not resolved to the IP of lmms.io

### ISSUE THREAD

**Issue by sitzer** [LMMS/lmms.io#336]
Maybe it's  a feature and not a bug, but www.lmms.io is leading to 68.183.100.144 what gives me a welcome to nginx Screen...
just lmms.io works fine

Sometimes I show people LMMS in Seminars and to write down the address on the chart board I write "www.lmms.io" as everybody understand it's a Website and is able to type it...

Cheers and thanks for your work

**Comment by tresf** [comment]
```bash
sudo nano /etc/nginx/conf.d/redirect.conf
```

```json
server {
    server_name www.lmms.io;
    return 301 $scheme://lmms.io$request_uri;
}
```

This fixes http://www.lmms.io.  Unfortunately, https will not work with our current certificate.
