### ISSUE TITLE
Error 500 on download page when 'analytics.js' is blocked

### ISSUE THREAD

**Issue by Galaxy621** [LMMS/lmms.io#337]
I attempted to download LMMS and was met with an error 500 on the download page. In console, it told me that the server gave error 500, and that analytics.js was blocked (which I believe is due to an ad blocker).
![console](https://user-images.githubusercontent.com/59318029/143722195-071aa86a-83e0-4c9c-ae84-490e417a444e.PNG)
![image](https://user-images.githubusercontent.com/59318029/143722216-fb4c658a-57b0-4abd-ae58-ef7a731d4a51.png)
After I disabled ad blocker, analytics.js was unblocked and the page started working.
![image](https://user-images.githubusercontent.com/59318029/143722229-42f6469f-d606-4798-9f49-24a01b963b42.png)

**Comment by liushuyu** [comment]
This shouldn't happen as I use adblocker myself and blocks Analytics. Is the issue still present?

**Comment by tresf** [comment]
Closing due to lack of update from the OP.
