### ISSUE TITLE
Add BOL9 to Showcase tab

### ISSUE THREAD

**Issue by Monospace-V** [LMMS/lmms.io#348]
The [Showcase](https://lmms.io/showcase) section of lmms.io has the BOL links, but they aren't shown here yet. It's there on the [Competitions](https://lmms.io/competitions) tab though.
Its results were announced about three months ago. Seems like these should be added soon.

**Comment by liushuyu** [comment]
Fixed in fedcb4823dbdb96353c51a3b43ec31a065d1cdae
