### ISSUE TITLE
LSP "Drum'n'Bass" projects page lists no results

### ISSUE THREAD

**Issue by lujlujluj** [LMMS/lmms.io#358]
When i visit https://lmms.io/lsp/?action=browse&category=Projects&subcategory=Drum'n'Bass&sort=date
by clicking on the Drum'n'Bass category in the Projects list.

The page gives no result.

![image](https://user-images.githubusercontent.com/6849253/229825765-c87e4424-bc09-4068-af56-b785f212fcf1.png)

Firefox 111.0.1 (64-bit / flatpak)

**Comment by WebSnke** [comment]
I think that's because there is a ' in the title. I suppose we change it to ["Drum and bass"](https://en.wikipedia.org/wiki/Drum_and_bass). I would really like to resolve this issue but I can't open the page as described in #360.
