### ISSUE TITLE
Sharing Platform section does not open on localhost

### ISSUE THREAD

**Issue by WebSnke** [LMMS/lmms.io#360]
I just tried to go to http://localhost:8000/lsp but there was just a blank page showing up.

This is what PHP was showing in the console:
```bash
[Mon Apr 24 18:38:34 2023] [::1]:32770 [500]: GET /lsp - Uncaught PDOException: could not find driver in /home/websnke/Downloads/lmms.io/public/lsp/dbo.php:79
Stack trace:
#0 /home/websnke/Downloads/lmms.io/public/lsp/dbo.php(79): PDO->__construct()
#1 /home/websnke/Downloads/lmms.io/public/lsp/dbo.php(195): get_db()
#2 /home/websnke/Downloads/lmms.io/public/lsp/index.php(92): get_latest()
#3 /home/websnke/Downloads/lmms.io/public/lsp/index.php(22): process_params()
#4 {main}
  thrown in /home/websnke/Downloads/lmms.io/public/lsp/dbo.php on line 79
[Mon Apr 24 18:38:34 2023] [::1]:32770 Closing
```

I followed the instructions on the README.md file and the other pages show up just fine.

**Comment by WebSnke** [comment]
The reason why it didn't work was because I started the PHP server without sudo. I think that should be mentioned as part of the README.md though.

**Comment by tresf** [comment]
@WebSnke thanks for volunteering to help with the LSP!  Since the LSP database has a bunch of hashed passwords, we can't share it unless we first scrape the passwords.

If you're still interested in helping out, ping me on #website on Discord.
