### ISSUE TITLE
Nightly downloads working sporadically

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms.io#362]
After merging #326, per https://github.com/LMMS/lmms.io/pull/351#discussion_r1197359352

```json
{"count":11,"value":"Uri expired"}
```

Possible workaround is to decrease the `ttl` cache time: https://github.com/LMMS/lmms.io/blob/e50a05212f40d996630ea398bfb76b765fc92530/config/packages/github_api.yaml#L8

**Comment by tresf** [comment]
> Possible workaround is to decrease the `ttl` cache time:

Done via ee21743.  Awaiting some more feedback.

**Comment by PhysSong** [comment]
@tresf Close?

**Comment by tresf** [comment]
Closed via ee21743.
