### ISSUE TITLE
Error 500 - Windows nightly versions NOT downloadable

### ISSUE THREAD

**Issue by pigeonskiller** [LMMS/lmms.io#366]
Error 500 - Windows nightly versions NOT downloadable

**Comment by tresf** [comment]
@pigeonskiller can you try again?  They're working for me.

**Comment by pigeonskiller** [comment]
Now working.Thanks.Il 28 ago 2023 18:25, Tres Finocchiaro ***@***.***> ha scritto:
@pigeonskiller can you try again?  They're working for me.

**Comment by tresf** [comment]
Pretty sure this issue is fixed.  Please request us to reopen if you believe it was closed in error.
