### ISSUE TITLE
nightly version commit hashes don't match any commits in the lmms repository

### ISSUE THREAD

**Issue by 1e1001** [LMMS/lmms.io#375]
hi this is likely mostly unrelated to the website, sorry,

a couple of times i've tried to debug issues that people have had with nightly lmms (and have needed to reproduce things for myself), and the commits don't match any on the repository

for example, the latest version listed on the website is gc991a85ee, which does not exist in the LMMS/lmms repository

i'm curious as to where these hashes are coming from if it's not the repository itself

**Comment by DomClark** [comment]
The version on the website is the commit hash prefixed with "g", as this matches the version displayed in LMMS, which is the version produced by running `git describe`. You'll find that `c991a85ee` does exist in the repository (and is the latest as of writing).

**Comment by 1e1001** [comment]
oh that makes so much sense, i forgot what a hexadecimal was!
