### ISSUE TITLE
Change default licence on LSP

### ISSUE THREAD

**Issue by Sti2nd** [LMMS/lmms.io#54]
Default licence (what is selected if you don't change it) could be some other than Artistic Licence 2.0, cause that doesn't allow remixing(?) and is less free than others. LMMS aims to promote freedom? Artistc licence is chosen as default now cause it is in alphabetical order.

Also updating the licences (add more of them? like v2, v3) cause some of them is rarely used and perhaps not used at all for music projects?

**Comment by tresf** [comment]
> think that the default licence should be CC BY (Attribution)

Sounds reasonable.  Done via 376972f.
