### ISSUE TITLE
LSP not allowing new registrations

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms.io#69]
http://lmms.io/lsp/?action=register

Users are presented with `invalid security code` error on new LSP regardless if the code was typed properly or not.

![screen shot 2014-10-19 at 4 49 43 pm](https://cloud.githubusercontent.com/assets/6345473/4694659/87d5cc94-57d1-11e4-9eb6-0e3dfaed7166.png)

**Comment by johnbaldwin19550** [comment]
This is still a problem for me.   I'd like to register, but I can't.  Please fix this.

**Comment by badosu** [comment]
@tresf Can I help with this in some way?

**Comment by tresf** [comment]
Working fine here... 

![image](https://cloud.githubusercontent.com/assets/6345473/6050356/ccd4ec84-ac8c-11e4-8a19-800cc188eea1.png)

**Comment by johnbaldwin19550** [comment]
Well, that's confusing.  It's not working for me, and I've tried it about 15 times.  Could it be that my browser is to blame?  Is there some plugin I need to install for this to work?  I'm using firefox 35.0.1 on Ubuntu 14.04.
![error](https://cloud.githubusercontent.com/assets/8584693/6051156/a7ff02ee-ac93-11e4-9992-e1a275562802.png)

**Comment by tresf** [comment]
> . Could it be that my browser is to blame? Is there some plugin I need to install for this to work? I'm using firefox 35.0.1 on Ubuntu 14.04.

Hmm... Possibly.  Do you have privacy mode enabled?  Someone here could just as easily create it on behalf of you and email you the password, but I too would like to know the cause of this problem.

-Tres

**Comment by johnbaldwin19550** [comment]
No privacy mode.  Nothing from the console either.  I'll keep looking.

**Comment by johnbaldwin19550** [comment]
Well, it worked in Chrome.  Not the first time, though.  I tried a different password the second time.  Is it possible that the page reports that the security code was invalid, regardless of what type of error occurred?

**Comment by badosu** [comment]
@johnbaldwin19550 I guess this was probably a cache issue. @tresf PR that fixes this issue probably creates a new session code that is stored on the cookie or on a javascript file, your browser was probably trying to use the old one so the application thought you were trying to forge a valid request with malicious intent.

**Comment by tresf** [comment]
Yeah, that security code is smoke and mirrors really.  


https://github.com/LMMS/lmms.io/blob/master/public/lsp/register.php#L34

@badosu is correct, it could be session related.  I wrote it quickly to deter robot registrations but we should really move to something more comprehensive.
