### ISSUE TITLE
LSP embed soundcloud urls

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms.io#71]
Enhancement request to allow the LSP to auto-embed soundcloud and possibly youtube urls.

This will require some small tweaks to the `get_json_data()` function.

**Comment by tresf** [comment]
@Umcaruje must have some broken logic when looking for word boundaries... Perhaps the `-` dash in the URL?

-Tres

**Comment by tresf** [comment]
Nope not the dash or the underscore... order... @Umcaruje this isn't working when he types text before the URL.  If I change his post to put the link before the text it works fine.

-Tres

**Comment by Umcaruje** [comment]
Wait, it started magically working again...

**Comment by Umcaruje** [comment]
https://lmms.io/lsp/?content=update&file=6105

**Comment by tresf** [comment]
Ah... I accidentally fixed it... Put a newline after it and it works.

**Comment by Umcaruje** [comment]
Ohh wait a second, I know what is the problem. For it not to process playlists, I had to make the regex look for a whitespace character after the link ends. All these iframe and playlist hacks are really uglyfying the code...

**Comment by tresf** [comment]
:cry: 

.
.
.
.
.

.
.
.
.
.
.
.
.





:smile:

**Comment by Umcaruje** [comment]
I have an idea that would solve these problems: but one can say its a bit ugly and redundant: What if every description started with a space and ended with one? Would something like that be possible?

**Comment by tresf** [comment]
> I have an idea that would solve these problems: but one can say its a bit ugly and redundant: What if every description started with a space and ended with one? Would something like that be possible?

If it fixes it, it won't hurt anything.  I'm perfectly fine with hacked solutions for as interim solutions.  I remember originally when we started link parsing you recommended leveraging a 3rd party library.... perhaps we're ready for that.

Use of the Twig framework can really kickstart the LSP rewrite... perhaps it is time?  Or perhaps we hack together another temp fix until we do it proper.  I'm fine with either. 

-Tres

**Comment by Sti2nd** [comment]
:+1: Yes, you told me yesterday
