### ISSUE TITLE
Front page

### ISSUE THREAD

**Issue by Sti2nd** [LMMS/lmms.io#77]
I tried to think about it from a potential new user perspective. What do I want from the web page if I don't know what LMMS is, or have heard about it but don't know what it can do? What I probably ruined by rearranging the sections is the aesthetics. 

I moved the problem and sharing section to the bottom, and in their place came screenshots and featuring. 
![lmms home](https://cloud.githubusercontent.com/assets/6373430/4816638/76166f9c-5ee1-11e4-9a53-da89171b8edd.png)
The first two sections is brilliant, a brief description and download buttons. This is no doubt what potential new users are looking for. Then the reason for this rearrangement was really to get more useful info about the program LMMS to the top, so the user wouldn't have to scroll all the way to the bottom, that is why the screenshots (says more than x words) and the featuring section comes next. I have no idea whether sharing or solving problems is what a user would want to learn about first, they are both very important IMO! Only not so important for a first viewer, and a first viewer wouldn't know how to navigate around on the site (though scrolling isn't hard).

The LMMS commercial video could definitely be placed in the featuring section's position in my mockup!! Video is better than a thousand images?

**Comment by tresf** [comment]
> Please make the appropriate changes and do a pull request. :+1:

This never happened and the OP has since become inactive.  Closing.
