### ISSUE TITLE
Jumbotron background image

### ISSUE THREAD

**Issue by Lukas-W** [LMMS/lmms.io#81]
I heard some voices expressing their dislike for the background image of the jumbotron, saying the flower-like pattern wouldn't fit a DAW. In case this opinion is shared by more people, I made an alternative for it.
I'm not saying it's better or that it should replace the old one, but I'm interested in hearing your thoughts about it.
![screen shot 2014-11-01 at 22 36 41](https://cloud.githubusercontent.com/assets/2879917/4873375/94b48246-620f-11e4-8542-d182d621749e.png)

**Comment by tresf** [comment]
We've lived with it for this long.  Please reopen if "dislike for the background image" becomes a concern.
