### ISSUE TITLE
Dated wiki content

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms.io#99]
@Umcaruje's notes:

So, I've been doing a lot of categorizing of the articles on the wiki. I categorized all the Pages that need work into 3 categories:
+ [Incomplete](http://lmms.sourceforge.net/wiki/index.php/Category:Incomplete)
+ [Out of Date](http://lmms.sourceforge.net/wiki/index.php/Category:Out_of_date)
+ [Too Complex](http://lmms.sourceforge.net/wiki/index.php/Category:Too_complex)

So if you are planning to work on the wiki (hint hint: @Spekular) you should work on the articles from those categories.

<s>The second thing I wanted to talk about is that we should probably remove most of the old articles. They are full of non-working pictures and weird structure that does not fit in the current wiki structure. Since we are having a new site, I think that the wiki should start with a clean slate (only 1.0+ articles). </s>(fixed)

I'd love to hear your guys's opinion on this. :beer: 

@tresf's notes:

Ticked items are fixed.

- [x] Do we have a need for the [wiki news](http://lmms.sourceforge.net/wiki/index.php/News_Archive)?
 *  it currently points to our sourceforge download page which should be updated.
 *  it seems like a redundant place to have announcements
 *  I cannot imagine anyone "subscribes" to the wiki news, right? So these announcements sort of get in the way IMO
- [x] Do we need a [contact page](http://lmms.sourceforge.net/wiki/index.php/Contact)
 *  We already have a "get-involved" page which has the proper channels of contacting us.
- [x] "Tip of the day" should have a better title unless we plan to implement this in our code.
 * I personally believe these should be combined with FAQ (possibly consider combining the formats to something a bit more condensed)
- [x] Can we review these [troubleshooting steps](http://lmms.sourceforge.net/wiki/index.php/Troubleshooting)?  
 * These are very platform specific, so we should consider a rewrite.
- [x] "Artist documentation" is a bit misleading of a title
- [x] We should probably make our theming article front row and center.
 * Musicians are artists, right? I don't even like this category title.
- [x] Writers section
 * Do we need this?  Couldn't we just reference some wikimedia standards?
 * I think this is misleading as well, since writing a wiki isn't necessarily a "writers" section.  I've authored a lot of wiki articles and I've never consider myself a writer.
- [x] Wiki ToDo
 * Again, this should be front-row and center, but it's much more than the wiki.  Uros fixed a bunch of source files with the old software name in it and that helps the project quite a bit.  I would suggest we just add what's missing from the getting-invovled page and then remove that.

I really don't mind redundancy, but I think we should avoid it because it makes things dated and harder to maintain.   Anything that has a GitHub or website equivalent, I vote we move it, hotlink it or whatever.  I don't want our wiki page to be a portal to our stuff, we already have one of those. :)

-Tres

**Comment by Umcaruje** [comment]
The wiki has been updated to version `1.24.1` and pages are being replaced -  `1.0:Manual` will now become `Manual` etc.

**Comment by tresf** [comment]
:+1:

**Comment by Umcaruje** [comment]
@Lukas-W I want to set up the wiki to use this skin: http://www.mediawiki.org/wiki/Skin:Chameleon

Could you explain how I can add it to our current Composer setup?

**Comment by tresf** [comment]
@Umcaruje, is it set up locally already?

**Comment by Umcaruje** [comment]
Ok, so wiki now uses Font Awesome. I added a few templates: https://lmms.io/wiki/index.php?title=Templates#Font_Awesome for easy access. Say hi to the new Main page: 
![newmainpage](https://cloud.githubusercontent.com/assets/6282045/5617480/9814e9f2-950f-11e4-9b71-f01c28e1d6dd.PNG)

**Comment by tresf** [comment]
Very nice!

Can we remove the links to the home page and forum now?  Also, not sure how to fix this, but the tile "Main Page" is misleading, it should probably say something about Documentation or Wiki (eventually at least).

**Comment by tresf** [comment]
Also, this redirect link is broken:

https://lmms.io/documentation/1.0:Getting_Started

**Comment by Umcaruje** [comment]
>Also, this redirect link is broken:

>https://lmms.io/documentation/1.0:Getting_Started

Can a global recache be done? (@Lukas-w) It seems as some pages cached while others were moving, so these broken are the result of that.

>Can we remove the links to the home page and forum now? Also, not sure how to fix this, but the tile "Main Page" is misleading, it should probably say something about Documentation or Wiki

Removed the links, I am not comfortable with changing the Main Page name yet, I have to do some investigation first :)

**Comment by tresf** [comment]
> I am not comfortable with changing the Main Page name yet, I have to do some investigation first :)

Yeah I agree... Perhaps we tackle this on the delivery side only... @Lukas-W shall we put a custom title on the `twig` side of our wiki pages which represent that they are Documentation/Wiki?

**Comment by Umcaruje** [comment]
>shall we put a custom title on the twig side of our wiki pages which represent that they are Documentation/Wiki?

Or I can remove the tittle and add a custom Heading :), I think that is the most painless solution.

**Comment by tresf** [comment]
> Or I can remove the tittle and add a custom Heading :), I think that is the most painless solution.

Ok... I just don't want to muck up the way it looks in the actual Wiki instance, but you'd be a better judge of that.

**Comment by Sti2nd** [comment]
> Also, this redirect link is broken: https://lmms.io/documentation/1.0:Getting_Started

Where did you find that? Can reproduce by pasting the link, but not through any Getting Started link on lmms.io/documentation

**Comment by tresf** [comment]
> Where did you find that?

Old URL, which was promised to work after page renames (i.e. standard testing )

**Comment by Sti2nd** [comment]
Oh, now I get it, you cannot click it either. It goes to https://lmms.io/documentation/Getting_Started&redirect=no which should go to https://lmms.io/documentation/Getting_Started

**Comment by Umcaruje** [comment]
Well that's something in the `RemWiki.php` I don't know how to fix it

**Comment by Sti2nd** [comment]
Remove &redirect=no ? Haha, such joke

**Comment by tresf** [comment]
Very cool!

`<span>`Not too bad`</span>`

Take out LMMS please tho.  And for consistency purposes, perhaps we just use "Documentation" ?  :) Oh yeah, and can we fix the span tags? :)

![image](https://cloud.githubusercontent.com/assets/6345473/5620174/43a12f6a-94f7-11e4-900e-875d0356536b.png)

**Comment by Umcaruje** [comment]
Done.

**Comment by tresf** [comment]
:+1:

**Comment by Lukas-W** [comment]
> Can a global recache be done?

Yes, removing all files in `/tmp/wiki/` via SSH should do the trick.

**Comment by Lukas-W** [comment]
The https://lmms.io/documentation/Getting_Started&redirect=no showing a blank page problem looks like a bug in the [`documentationPage($page)`](https://github.com/LMMS/lmms.io/blob/master/views.php#L7) function in `views.php`. My guess is that the `&redirect=no` part is not being stripped and the script therefore looks for a page called `Getting_Started&redirect=no`.

**Comment by tresf** [comment]
These troubleshooting steps really need to be cleaned up.  I see stuff in there from 0.3.0.  @mikobuntu @Umcaruje @softrabbit can we debunk/move this to the GitHub wiki section because these don't really seem to be common end-user troubleshooting steps and I'm not sure the GDB steps offer that much when using a standard build, right?

**Comment by Umcaruje** [comment]
Just a 'lil update on this: I edited the original post and turned it into a task list. 

As for the articles, all of them are transferred now. So there is no longer a page named `1.0:Getting Started`, now its just `Getting Started`. That means that we don't have to duplicate all the pages and create new manuals for 1.1, 1.2 etc. but to simply update the current pages when that's needed.

**Comment by tresf** [comment]
All items appear to have been addressed.  Thanks! Closing.
